### ISSUE TITLE
xml doc: arity= selector in <name> tags doesn't work for types

### ISSUE THREAD

**Issue by attah** [erlang/otp#4927] opened 2021-06-02 09:15 UTC
**Describe the bug**
Found when doing:
https://github.com/erlang/otp/pull/4926

This adds types with the same name but different arity to a module (gen_staem in this case) that has xml documentation for those types.
The doc build then fails with:
`Error in gen_statem:init_result: ambiguous type`

If i then add, arity="2" to the <name> tag for init_result in gen_statem.xml, it fails with
`Error in gen_statem:init_result/2: unknown spec`
(same with adding arity 1, and with adding <name>-tags for all versions of the type like in the PR)
There looks to be code to handle this in the xsl, but it seems unused.

**To Reproduce**

1. Add new arity of a xml-doc'ed type.

**Expected behavior**
Docs work, at least after adding arity="X"

**Affected versions**
Tested with 24.0.1, probably many.

**Additional context**

**Comment by attah** [comment] 2021-08-06 15:47
Solved it... apparently the selector for type arity is not `arity`, but `n_vars`, but it is not like that yields an error, it just starts looking up function specs instead of types (xsl function find_spec).

**Comment by lthor** [comment] 2021-09-20 13:39
Closing this issue because the problem is solved.
Better documentation in this area is on it's way and we will create an internal job ticket about attribute checking.

**Closed by lthor** 2021-09-20 13:39 UTC
Labels: team:PS, bug

**Comment by attah** [comment] 2021-09-20 16:41
That and an actually relevant error message should do it. :+1:
