### ISSUE TITLE
"a term is constructed, but never used" warning false positive in Erlang 24 compiler but not 23

### ISSUE THREAD

**Issue by michaelklishin** [erlang/otp#4576] opened 2021-03-04 03:00 UTC
Team RabbitMQ has started working on Erlang 24 compatibility and with some dependency updates/replacement, most things already work. However, we run into a curious compiler warning in our CI environment which Erlang 23 does not reproduce.

## The Warning

```
 ERLC   app_utils.erl code_version.erl credit_flow.erl delegate.erl delegate_sup.erl file_handle_cache.erl file_handle_cache_stats.erl gen_server2.erl lager_forwarder_backend.erl mirrored_supervisor.erl mnesia_sync.erl pmon.erl priority_queue.erl rabbit_amqp_connection.erl rabbit_amqqueue_common.erl rabbit_auth_backend_dummy.erl rabbit_auth_mechanism.erl rabbit_authn_backend.erl rabbit_authz_backend.erl rabbit_basic_common.erl rabbit_binary_generator.erl rabbit_binary_parser.erl rabbit_cert_info.erl rabbit_channel_common.erl rabbit_command_assembler.erl rabbit_control_misc.erl rabbit_core_metrics.erl rabbit_data_coercion.erl rabbit_env.erl rabbit_error_logger_handler.erl rabbit_event.erl rabbit_exchange_type.erl rabbit_framing_amqp_0_8.erl rabbit_framing_amqp_0_9_1.erl rabbit_heartbeat.erl rabbit_http_util.erl rabbit_json.erl rabbit_log.erl rabbit_log_osiris_shim.erl rabbit_log_ra_shim.erl rabbit_misc.erl rabbit_msg_store_index.erl rabbit_net.erl rabbit_nodes_common.erl rabbit_numerical.erl rabbit_password_hashing.erl rabbit_pbe.erl rabbit_peer_discovery_backend.erl rabbit_policy_validator.erl rabbit_queue_collector.erl rabbit_registry.erl rabbit_registry_class.erl rabbit_resource_monitor_misc.erl rabbit_runtime.erl rabbit_runtime_parameter.erl rabbit_semver.erl rabbit_semver_parser.erl rabbit_ssl_options.erl rabbit_types.erl rabbit_writer.erl supervisor2.erl vm_memory_monitor.erl worker_pool.erl worker_pool_sup.erl worker_pool_worker.erl
compile: warnings being treated as errors
src/rabbit_amqp_connection.erl:17:17: a term is constructed, but never used
%   17|                 rabbit_log:debug("file ~p, line ~p - connection process ~p not alive: ~p~n",
%     |                 ^

src/rabbit_amqp_connection.erl:21:17: a term is constructed, but never used
%   21|                 rabbit_log:debug("file ~p, line ~p - failed to get amqp_params from connection process ~p: ~p~n",
%     |                 ^

erlang.mk:5441: recipe for target 'ebin/rabbit_common.app' failed
```

## The Line in Question

The line in question is [`rabbit_amqp_connection.erl#L17`](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit_common/src/rabbit_amqp_connection.erl#L17). I don't see what binding
would be unused in it.

I also don't think it's realistic for us to change every line where we log to something like this

``` erl
_ = rabbit_log:debug("file ~p, line ~p - connection process ~p not alive: ~p~n",
                                 [?FILE, ?LINE, ConnPid, Error]),
```

So perhaps this warning is a bit too aggressive or this is a false positive?

## Erlang master Commit Ref

This CI image was produced off of 0a787390be771f5ae1fd44fcea25ab9bf9dfb833

**Comment by michaelklishin** [comment] 2021-03-04 03:53
Upgrading locally to the tip of `master` helped me reproduce locally. It must be something recent because I previously had a version a few commits later than 24-rc.1. I can try to `git bisect` if needed.

**Comment by bjorng** [comment] 2021-03-04 06:09
Downloading a copy of `rabbit_amqp_connection.erl` that you pointed out and compiling it, the compiler emits no warnings.

I then tried to compile the entire `rabbitmq-server` project (on my Mac), but it failed:

```
make[1]: Entering directory '/Users/bjorng/git/rabbitmq-server/deps/rabbit_common'
 DEP    lager (3.9.1)
 DEP    jsx (2.11.0)
 DEP    recon (2.5.1)
make[2]: Entering directory '/Users/bjorng/git/rabbitmq-server/deps/lager'
 DEPEND lager.d
 ERLC   error_logger_lager_h.erl lager.erl lager_app.erl lager_backend_throttle.erl lager_common_test_backend.erl lager_config.erl lager_console_backend.erl lager_crash_log.erl lager_default_formatter.erl lager_file_backend.erl lager_format.erl lager_handler_watcher.erl lager_handler_watcher_sup.erl lager_manager_killer.erl lager_msg.erl lager_rotator_behaviour.erl lager_rotator_default.erl lager_stdlib.erl lager_sup.erl lager_transform.erl lager_trunc_io.erl lager_util.erl
 APP    lager.app.src
make[2]: Leaving directory '/Users/bjorng/git/rabbitmq-server/deps/lager'
make[2]: Entering directory '/Users/bjorng/git/rabbitmq-server/deps/jsx'
 DEPEND jsx.d
 ERLC   jsx.erl jsx_config.erl jsx_consult.erl jsx_decoder.erl jsx_encoder.erl jsx_parser.erl jsx_to_json.erl jsx_to_term.erl jsx_verify.erl
Old inliner: threshold=0 functions=[{doublequote,5},
                                    {singlequote,5},
                                    {maybe_replace,2},
                                    {format_number,1},
                                    {handle_event,3}]
 APP    jsx.app.src
make[2]: Leaving directory '/Users/bjorng/git/rabbitmq-server/deps/jsx'
make[2]: Entering directory '/Users/bjorng/git/rabbitmq-server/deps/recon'
 DEPEND recon.d
 ERLC   recon.erl recon_alloc.erl recon_lib.erl recon_map.erl recon_rec.erl recon_trace.erl
Old inliner: threshold=0 functions=[{insert,2},{merge,2}]
 APP    recon.app.src
make[2]: Leaving directory '/Users/bjorng/git/rabbitmq-server/deps/recon'
Error: No Makefile to build dependency /Users/bjorng/git/rabbitmq-server/deps/credentials_obfuscation.
make[1]: *** [erlang.mk:4512: deps] Error 2
make[1]: Leaving directory '/Users/bjorng/git/rabbitmq-server/deps/rabbit_common'
make: *** [erlang.mk:4512: deps] Error 2
```

I then tried to compile just the file, but using the `lager_transform` parse transform. Still no warnings.

In your build environment, are you using the latest version of `lager` that include the https://github.com/erlang-lager/lager/pull/537 and https://github.com/erlang-lager/lager/pull/539 pull request?

If the problem persists with the latest version of `lager`, please provide with me a minimal example so that I can reproduce the problem myself.

**Comment by michaelklishin** [comment] 2021-03-04 09:51
We have just moved to Lager 3.9.1.

**Comment by michaelklishin** [comment] 2021-03-04 13:46
We are arriving at the conclusion that this is an issue caused by Lager transforms. Perhaps the compiler is stricter now than it used to be. I will try with Lager master, and if that does not work out, we will proceed with replacing Lager with the standard OTP logger. It was in the cards for a while anyway.

**Comment by bjorng** [comment] 2021-03-04 15:23
#4545 that I recently merged can cause the compiler to emit more warnings.

Since it seems that you have solved the problem, I will close this issue.

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-04 17:03
@michaelklishin, if possible could you open an issue in `lager` even if you decide to move to `logger` if you figure out what where the issue lies? I haven't suffered the issue you describe here, but would be willing to fix stuff in `lager` (until we move to `logger`) to prevent it. Thanks.

**Comment by michaelklishin** [comment] 2021-03-05 00:03
@paulo-ferraz-oliveira sure, the only known way to reproduce is to try to build RabbitMQ, though, which is not a massive task but not a trivial standalone example by any means.

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-05 05:29
@bjorng, the issue is caused specifically by these lines:

* https://github.com/erlang-lager/lager/blob/master/src/lager_transform.erl#L203
* https://github.com/erlang-lager/lager/blob/master/src/lager_transform.erl#L211

which build an `{error, _}` tuple. We're [discussing the possibility](https://github.com/erlang-lager/lager/issues/546#issuecomment-791069964) of replacing that with`ok`, but I'm wondering, in any case, if there's any other way to move forward without breaking the existing implementation. Your help would be appreciated.

**Comment by bjorng** [comment] 2021-03-05 06:06
@paulo-ferraz-oliveira, I can think of a few other possible solutions.

If the `lager_transform` could do some simple analysis to see whether the `error` tuple would be used or not, it could emit `ok` when the following code ignores the value, and the `error` tuple otherwise. I don't know how hard that would be to do.

If that is not feasible, the `fun` trick could be modified to still work. What you have now is:

```
fun() -> {error,sink_not_configured} end()
```

To prevent inlining of the `fun`, that could be changed to:

```
UniqueNameForFun = fun(_) -> {error,sink_not_configured} end,
UniqueNameForFun(UniqueNameForFun)
```

A third possibility would be if we added a way to suppress the warnings for useless building of terms. We have been thinking about doing that anyway for many years.

**Comment by bjorng** [comment] 2021-03-05 06:24
@paulo-ferraz-oliveira, I think I have another, much superior solution.

There is documented way to mark an abstract construct as compiler generated, using [erl_anno:set_generated/2](http://erlang.org/doc/man/erl_anno.html#set_generated-2), which will suppress warnings.

I have not tested it, but I think that the following should work:

```
[{tuple, erl_anno:set_generated(true, Line), [{atom, Line, error},{atom, Line, lager_not_running}]}]
```

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-05 11:18
Oh, this last one's nice. I'll try it out, thanks.

**Closed** 2021-03-09 12:48 UTC
Labels: bug, team:VM
