### ISSUE TITLE
The same input + regex for re:run/3 in a tight loop leads to inconsistent results

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#5150] opened 2021-08-25 06:45 UTC
**Describe the bug**

Take this module:

```erlang
-module(trim).
-export([trim/1, sorted_loop/2]).

trim(Entry) when is_binary(Entry) -> do_trim(Entry).
do_trim(<<Rest/bits>>) -> Rest.

sorted_loop(Fun, Attempts) ->
  Results = lists:map(Fun, lists:seq(1, Attempts)),
  io:format("~p~n", [lists:usort(Results)]).
```

Now compile this module with `erlc trim.erl` and then run this:

    erl -noshell -eval 'trim:sorted_loop(fun(_) -> re:run(trim:trim(<<"EmployeeEmailAddress">>), <<"([a-z])([A-Z])">>, [global]) end, 1000000), erlang:halt().'

The expected result is this (to match on both eE and lA):

`` `erlang
[{match,[[{7,2},{7,1},{8,1}],[{12,2},{12,1},{13,1}]]}]
```

But on Erlang/OTP 23, you might find the following results:

```erlang
[{match,[[{7,2},{7,1},{8,1}]]},
 {match,[[{7,2},{7,1},{8,1}],[{12,2},{12,1},{13,1}]]}]
```

or this:

```erlang
[nomatch,
 {match,[[{7,2},{7,1},{8,1}]]},
 {match,[[{7,2},{7,1},{8,1}],[{12,2},{12,1},{13,1}]]}]
```

Which means the same inputs is leading to different results.

Some important notes:

  1.  I can reproduce it with 100_000 attempts but the example above uses a million to be sure

  2. If I remove the trim:trim/1 call, I can no longer reproduce the issue

  3. If I compile all code (instead of using -eval), I can no longer reproduce the issue

  4. Removing the global option also reproduces the bug as it returns `nomatch` in some cases

**Affected versions**

I can reproduce the bug on Erlang/OTP 23.1 but not on Erlang/OTP 24. I don't know if it is because the bug has been fixed or a side-effect, so I thought I would report it anyway.

Thank you!

**Comment by garazdawi** [comment] 2021-08-25 07:45
hmm, I wasn't able to reproduce it with your Erlang reproducer, but I was able to do it with the original Elixir example.

**Comment by josevalim** [comment] 2021-08-25 08:53
Interesting! Can you reproduce it if you use the Elixir example but call :trim.trim instead of String.trim?

**Comment by garazdawi** [comment] 2021-08-25 09:35
> Can you reproduce it if you use the Elixir example but call :trim.trim instead of String.trim?

yes.

**Comment by matt-glover** [comment] 2021-08-25 12:34
I could only reproduce it with the Erlang example once I bumped the number of iterations at the end of the `erl` call from 1 million to 2 million. Then it produced the unexpected results relatively consistently for me on 23.2.7 `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.1.8`.

**Comment by garazdawi** [comment] 2021-08-30 07:55
and it does not happen in the JIT because [another optimization](https://github.com/erlang/otp/blob/164fc08/erts/emulator/beam/jit/x86/instr_bs.cpp#L1010) only made in the JIT makes sure that the code in `trim` does not create any subbinaries when a heap binary could have been created.

So the problem may only exist in the interpreter, though I would not be very surprised if there exist more ways to create subbinaries that trigger the GC optimization, so it needs to be fixed in the GC for both JIT and interpreter.

**Closed** 2021-09-02 07:14 UTC
Labels: team:VM, bug
