### ISSUE TITLE
zip:extract/2 out of memory on Windows

### ISSUE THREAD

**Issue by jonatanklosko** [erlang/otp#5913] opened 2022-04-20 11:44 UTC
**Describe the bug**

Calling `zip:extract/2` (with `cwd` option) on a 147MB archive crashes with

```
eheap_alloc: Cannot allocate 18446744072148144504 bytes of memory (of type "heap").
```

OS: Microsoft Windows Server 2022 10.0.20348 (windows-2022 on GitHub actions)

**To Reproduce**

* [script](https://github.com/jonatanklosko/__erl_zip_extract__/blob/83bb295c81b3f76f118a49bcc751ddff75a5f396/test.erl)
* [CI failure](https://github.com/jonatanklosko/__erl_zip_extract__/runs/6086354608?check_suite_focus=true#step:4:12)
* [erl_crash.dump](https://github.com/jonatanklosko/__erl_zip_extract__/releases/tag/log)

**Affected versions**

We initially run into this on 24.2 and then I verified it persist on 25.0-rc3.

**Comment by garazdawi** [comment] 2022-04-27 15:02
Seems like somewhere in the zlib code there is a sign extension gone wrong as `18446744072148144504 == 0xffffffffa2eed178`.

I'm unable to reproduce it using our built-in zlib on Linux, so will have to try again on Windows. Seems like there was a [new release of zlib](https://www.zlib.net/) one month ago, so maybe this has been fixed there or it is a problem in our code.

**Comment by garazdawi** [comment] 2022-04-28 07:28
I was unable to reproduce it on my local windows machine... but gh actions can reproduce it. @dgud can you see if you can reproduce it on your machine?

**Comment by dgud** [comment] 2022-04-28 08:31
No works with both 32b and 64b OTP-24.2 on windows for me.

**Comment by garazdawi** [comment] 2022-10-03 14:31
I can no longer reproduce this issue using github CI and https://imagemagick.org/archive/binaries/ImageMagick-7.1.0-portable-Q16-x64.zip (the binary seems to have been moved/updated). So I'm closing this issue.

**Closed by garazdawi** 2022-10-03 14:31 UTC
Labels: team:VM, bug

**Comment by jonatanklosko** [comment] 2022-10-03 14:54
@garazdawi sounds good, thank you!
