### ISSUE TITLE
OTP25 bus error on Mac OS Sonoma

### ISSUE THREAD

**Issue by rafaelgaspar** [erlang/otp#7687] opened 2023-09-26 20:48 UTC
**Describe the bug**
This have been known for a while since the beta, but I don’t see any issue here and the final version was released today.

**To Reproduce**
On Mac OS Sonoma, run `erlc` and you get a bus error.

While rebuilding it from source with XCode 15, it also fails in the same manner, after building `erlc` it fails running it to build ebin’s.

**Expected behavior**
It would be nice to know if there is any plans of fixing this for OTP25, or if only OTP26 will be supported going forward.

**Affected versions**
As far as I’m aware all versions below OTP26.

**Additional context**
https://elixirforum.com/t/bus-error-after-upgrading-to-sonoma-beta/56354?page=2
https://github.com/kerl/kerl/issues/450

**Comment by carflynn2009** [comment] 2023-09-26 21:50
I am getting the same issue installing Erlang OTP 25 using asdf

To Reproduce
On Mac OS Sonoma run `asdf install erlang 25.0.4`

If you already had OTP 25 before upgrade you get bus error if you run `iex` and if you remove and try to reinstall the asdf build fails

Expected behavior
It would be nice to know if there is any plans of fixing this for OTP25, or if only OTP26 will be supported going forward.

Affected versions
As far as I’m aware all versions below OTP26.

**Comment by westonlit** [comment] 2023-09-26 22:53
+1

I didn't know about the issue with macOS Sonoma, and I installed it today and cannot run apps using OTP 25 or build it from source.

**Comment by starbelly** [comment] 2023-09-27 02:22
This is fixed on maint-25. You can confirm this with `asdf install erlang ref:maint-25` (or compile as you normally would).

**Comment by carflynn2009** [comment] 2023-09-27 06:41
@starbelly does this fix only cover 25.0? I will give this a test and see if that fixes my issue

**Comment by carflynn2009** [comment] 2023-09-27 07:15
> This is fixed on maint. You can confirm this with `asdf install erlang ref:maint` (or compile as you normally would).
> 
> Specifically, this was fixed up per [82dd4a5](https://github.com/erlang/otp/commit/82dd4a54ad59dbac392ffca18498c1ea375a5981) and [291f3ed](https://github.com/erlang/otp/commit/291f3ed37b5c0ee1e8ca65fe8b746cb13b0551db) .
> 
> To note, I tested OTP 24, no issues there, only with OTP 25.

I have successfully been able to install `ref:maint` using asdf but how to i use a specific version of OTP25 that my asdf tool-versions require?

25.0.4 to be exact but any version of 25 will do

After i install  `ref:maint` and run `erl` i get `OTP26`

**Comment by rafaelgaspar** [comment] 2023-09-27 07:49
> I have successfully been able to install `ref:maint` using asdf but how to i use a specific version of OTP25 that my asdf tool-versions require?

That's not possible `maint` is the branch containing the latest released commits(see it as similar to a `production` branch), while the OTP25 lives in `maint-25`, so it's two separate branches. It's not an option you pass when compiling.



> Specifically, this was fixed up per [82dd4a5](https://github.com/erlang/otp/commit/82dd4a54ad59dbac392ffca18498c1ea375a5981) and [291f3ed](https://github.com/erlang/otp/commit/291f3ed37b5c0ee1e8ca65fe8b746cb13b0551db) .

@starbelly Do you know if those are cherry-pickable into `maint-25`? I'll give it a try anyway.

**Comment by carflynn2009** [comment] 2023-09-27 07:52
> > I have successfully been able to install `ref:maint` using asdf but how to i use a specific version of OTP25 that my asdf tool-versions require?
> 
> 
> 
> That's not possible `maint` is the branch containing the latest released commits(see it as similar to a `production` branch), while the OTP25 lives in `maint-25`, so it's two separate branches. It's not an option you pass when compiling.
> 
> 
> 
> 
> 
> 
> 
> > Specifically, this was fixed up per [82dd4a5](https://github.com/erlang/otp/commit/82dd4a54ad59dbac392ffca18498c1ea375a5981) and [291f3ed](https://github.com/erlang/otp/commit/291f3ed37b5c0ee1e8ca65fe8b746cb13b0551db) .
> 
> 
> 
> @starbelly Do you know if those are cherry-pickable into `maint-25`? I'll give it a try anyway.

maint will not help me in that case as I have always been able to install OTP26 but I need OTP25

**Comment by rafaelgaspar** [comment] 2023-09-27 07:53
> 25.0.4 to be exact but any version of 25 will do

@carflynn2009 I doubt they will do a new release for each non-major version, if this is fixed, you will probably get only on the latest OTP25 version. But compatibility wise, that should be good enough for almost everyone.

**Comment by carflynn2009** [comment] 2023-09-27 07:55
> > 25.0.4 to be exact but any version of 25 will do
> 
> 
> 
> @carflynn2009 I doubt they will do a new release for each non-major version, if this is fixed, you will probably get only on the latest OTP25 version. But compatibility wise, that should be good enough for almost everyone.

Yes latest OTP25 will work for what I need, hopefully this can get cherry picked into that version

**Comment by rafaelgaspar** [comment] 2023-09-27 08:04
> Specifically, this was fixed up per [82dd4a5](https://github.com/erlang/otp/commit/82dd4a54ad59dbac392ffca18498c1ea375a5981) and [291f3ed](https://github.com/erlang/otp/commit/291f3ed37b5c0ee1e8ca65fe8b746cb13b0551db) .

I just checked and both commits changes are present in `maint-25`.

**Comment by carflynn2009** [comment] 2023-09-27 08:16
> > Specifically, this was fixed up per [82dd4a5](https://github.com/erlang/otp/commit/82dd4a54ad59dbac392ffca18498c1ea375a5981) and [291f3ed](https://github.com/erlang/otp/commit/291f3ed37b5c0ee1e8ca65fe8b746cb13b0551db) .
> 
> I just checked and both commits changes are present in `maint-25`.
> 
> But still I can't compile it.

+1 

Does not compile for me either

**Comment by garazdawi** [comment] 2023-09-27 08:27
We are not as eager to update our MacOS you guys, so we don't have anyway to test this yet. Can you do a `git bisect start --first-parent maint OTP-25.3.2` and see which commit fixes the problem?

**Comment by rafaelgaspar** [comment] 2023-09-27 09:22
@garazdawi This is result of the git bisect.

```
b0c30263a0ef698244d898a95c9b9a40e67eac9c is the first bad commit
commit b0c30263a0ef698244d898a95c9b9a40e67eac9c
Author: Henrik Nord <henrik@erlang.org>
Date:   Wed May 18 09:57:03 2022 +0200

    Prepare for development

 OTP_VERSION              |   2 +-
 make/otp_version_tickets | 191 +----------------------------------------------
 2 files changed, 2 insertions(+), 191 deletions(-)
bisect found first bad commit
```

Not sure what to do with that though.

**Comment by kpy3** [comment] 2023-09-27 09:25
> @garazdawi This is result of the git bisect:
> 
> ```
> b0c30263a0ef698244d898a95c9b9a40e67eac9c is the first bad commit
> commit b0c30263a0ef698244d898a95c9b9a40e67eac9c
> Author: Henrik Nord <henrik@erlang.org>
> Date:   Wed May 18 09:57:03 2022 +0200
> 
>     Prepare for development
> 
>  OTP_VERSION              |   2 +-
>  make/otp_version_tickets | 191 +----------------------------------------------
>  2 files changed, 2 insertions(+), 191 deletions(-)
> bisect found first bad commit
> ```
> 
> Not sure what to do with that though.

Hm, looks like there is no code changes in that commit... 🤔

**Comment by Sgoettschkes** [comment] 2023-09-27 09:34
Shouldn't git bisect take the bad commit ref first? So it would be `git bisect start --first-parent OTP-25.3.2 maint`?

**Comment by garazdawi** [comment] 2023-09-27 09:47
Odd, try it without the `--first-parent` option and see if that work better.

Also as @Sgoettschkes noticed, the order of good and bad are switched because (in my git) `bad` has to be after `good`. So when doing bisect you need to switch the meaning of good and bad so that `good = broken` and `bad = works`.

**Comment by rafaelgaspar** [comment] 2023-09-27 09:59
> `git bisect start --first-parent OTP-25.3.2 maint`

```
$ git bisect start --first-parent OTP-25.3.2 maint
Some good revs are not ancestors of the bad rev.
git bisect cannot work properly in this case.
Maybe you mistook good and bad revs?
```

> Odd, try it without the `--first-parent` option and see if that work better.

Already tried, same commit is returned.

**Comment by rafaelgaspar** [comment] 2023-09-27 10:28
I see my mistake, I also need to invert the test script, running it now with !compile.

Also, somewhere in the middle of these commits the error message changes from `bus error` to `Internal error: jit: Cannot allocate executable memory. Use the interpreter instead.`

```
=== Entering application parsetools
erlc -W  -Werror +debug_info -I/Users/rafael.gaspar/Projects/ThirdParty/otp/lib/stdlib/include -Werror -o../ebin leex.erl
beam/jit/beam_jit_main.cpp:190:pick_allocator(): Internal error: jit: Cannot allocate executable memory. Use the interpreter instead.
make[3]: *** [../ebin/leex.beam] Abort trap: 6
make[2]: *** [opt] Error 2
make[1]: *** [opt] Error 2
make: *** [secondary_bootstrap] Error 2
```

**Comment by rafaelgaspar** [comment] 2023-09-27 10:43
So this is how a renamed things:

`git bisect start --term-new=fixed --term-old=unfixed --first-parent maint OTP-25.3.2`

And this is resulting commit:
```
3508ea39f8d144cb78bda5a2c326b4b6a9f0ce58 is the first fixed commit
commit 3508ea39f8d144cb78bda5a2c326b4b6a9f0ce58
Merge: 69f95cb444 69cd11ae60
Author: John Högberg <john@erlang.org>
Date:   Fri Mar 17 12:22:00 2023 +0100

    Merge pull request #7018 from jhogberg/john/erts/refactor-code-modification/OTP-18513

    erts: Refactor code modification

 erts/emulator/beam/beam_bif_load.c             |  22 +-
 erts/emulator/beam/beam_bp.c                   | 283 ++++++++++++++++++-------
 erts/emulator/beam/beam_bp.h                   |   7 +-
 erts/emulator/beam/beam_debug.c                |   7 +-
 erts/emulator/beam/emu/emu_load.c              |   2 +
 erts/emulator/beam/erl_bif_trace.c             |  32 ++-
 erts/emulator/beam/erl_lock_check.c            |   2 +-
 erts/emulator/beam/erl_nif.c                   | 144 ++++++++-----
 erts/emulator/beam/jit/arm/beam_asm.hpp        |   6 +-
 erts/emulator/beam/jit/arm/beam_asm_global.cpp |  12 +-
 erts/emulator/beam/jit/asm_load.c              |  92 ++++----
 erts/emulator/beam/jit/beam_asm.h              |  27 ++-
 erts/emulator/beam/jit/beam_jit_common.cpp     |  28 ++-
 erts/emulator/beam/jit/beam_jit_main.cpp       |  54 +++--
 erts/emulator/beam/jit/load.h                  |   4 +-
 erts/emulator/beam/jit/x86/beam_asm.hpp        |   6 +-
 erts/emulator/beam/jit/x86/beam_asm_global.cpp |  12 +-
 erts/emulator/beam/module.c                    |  91 ++++----
 erts/emulator/beam/module.h                    |  28 ++-
 erts/emulator/internal_doc/BeamAsm.md          |  14 +-
 erts/emulator/test/jit_SUITE.erl               |  18 +-
 21 files changed, 567 insertions(+), 324 deletions(-)
bisect found first bad commit
```

**Comment by garazdawi** [comment] 2023-09-27 11:08
Seems like the way we allocate JIT code in 25 has been disallowed in MacOS Sonoma. I don't think we can just apply the commit you found to 25 as that would also introduce other changes that I'm not sure we want on the 25 track.

What happens if you set `ERL_FLAGS="+JPperf map"` before building?

If you want to have a quick fix so that you can get on with your work you can disable the jit when compiling by setting: `KERL_CONFIGURE_OPTIONS="--disable-jit"`.

**Comment by Sgoettschkes** [comment] 2023-09-27 12:26
> If you want to have a quick fix so that you can get on with your work you can disable the jit when compiling by setting: KERL_CONFIGURE_OPTIONS="--disable-jit".

I can confirm that this is working with `asdf`. Thanks for unblocking me (and others) 😊!

**Comment by rafaelgaspar** [comment] 2023-09-27 12:30
> What happens if you set `ERL_FLAGS="+JPperf map"` before building?

```
=== Entering application parsetools
erlc -W  -Werror +debug_info -I/Users/rafael.gaspar/Projects/ThirdParty/otp/lib/stdlib/include -Werror -o../ebin leex.erl
+JPperf is not supported on this platform
```

> If you want to have a quick fix so that you can get on with your work you can disable the jit when compiling by setting: `KERL_CONFIGURE_OPTIONS="--disable-jit"`.


Using this:
```
export KERL_CONFIGURE_OPTIONS="--disable-jit"
asdf install erlang 25.3.2.6
```

Does compile it fine.

Thanks for the help, and let me know if you need help further investigating the root cause and possible solution for it without disabling JIT.

**Comment by jhogberg** [comment] 2023-09-27 12:43
> Thanks for the help, and let me know if you need help further investigating the root cause and possible solution for it without disabling JIT.

Sure, can you check if the problem comes back when you remove [this line](https://github.com/erlang/otp/blob/1e09a38783d984f8ea5c72e9b97ad73fe7a0b0ae/erts/emulator/beam/jit/beam_jit_main.cpp#L162) on `maint`?

**Comment by rafaelgaspar** [comment] 2023-09-27 13:04
> Sure, can you check if the problem comes back when you remove [this line](https://github.com/erlang/otp/blob/1e09a38783d984f8ea5c72e9b97ad73fe7a0b0ae/erts/emulator/beam/jit/beam_jit_main.cpp#L162) on `maint`?

I commented that line in `maint`(1e09a387) and unfortunately it builds fine.

**Comment by starbelly** [comment] 2023-09-27 13:05
> So this is how a renamed things:
> 
> `git bisect start --term-new=fixed --term-old=unfixed --first-parent maint OTP-25.3.2`
> 
> And this is resulting commit:
> 
> ```
> 3508ea39f8d144cb78bda5a2c326b4b6a9f0ce58 is the first fixed commit
> commit 3508ea39f8d144cb78bda5a2c326b4b6a9f0ce58
> Merge: 69f95cb444 69cd11ae60
> Author: John Högberg <john@erlang.org>
> Date:   Fri Mar 17 12:22:00 2023 +0100
> 


Beautiful! So what I can do is reset back to this commit on maint-25 then `git cherry-pick -m1 291f3ed37b5c0ee1e8ca65fe8b746cb13b0551db`  and that works 😅

**Comment by jhogberg** [comment] 2023-09-27 13:10
I’m not sure that’ll work well, if nothing else you’ll need to apply this too: https://github.com/erlang/otp/commit/74eee7564d64091dcf42f9361be5381f9fbec0ab

**Comment by starbelly** [comment] 2023-09-27 13:15
> I’m not sure that’ll work well, if nothing else you’ll need to apply this too: [74eee75](https://github.com/erlang/otp/commit/74eee7564d64091dcf42f9361be5381f9fbec0ab)

Oh, no one said anything about working well 😄 Merely just getting it to compile and run and finding a point in time for that.

**Comment by iAchilles** [comment] 2023-09-28 04:20
I faced with the same issue. 
MacOS Sonoma 14.0 (Mac Studio 2022 Apple M1 Max) OTP 25 - bus error,

but
MacOS Sonoma 14.0 (Macbook Pro 2019 2,6 GHz 6-Core Intel Core i7) - no any troubles. **OTP 25 works**

**Comment by rafaelgaspar** [comment] 2023-09-28 04:27
> I faced with the same issue. MacOS Sonoma 14.0 (Mac Studio 2022 Apple M1 Max) OTP 25 - bus error,
> 
> but MacOS Sonoma 14.0 (Macbook Pro 2019 2,6 GHz 6-Core Intel Core i7) - no any troubles. **OTP 25 works**

Makes sense that this is an ARM64 specific issue since it’s related to JIT compilation.

Thanks for the extra info on the issue, I did not had access to an Intel Mac running Sonoma at the moment.

**Closed** 2023-10-10 12:04 UTC
Labels: team:VM, bug

**Comment by jdmarshall** [comment] 2024-03-08 01:57
> OTP 25 works 

I cannot reproduce this. I get the same error with both.  All recent vintages of erlang fail with this same error.  

disabling jit also isn't working. It just changes the error:

> make[5]: *** [../../ebin/megaco_flex_scanner_handler.beam] Error 1

**Comment by garazdawi** [comment] 2024-03-08 07:12
> disabling jit doesn't work for me. It just changes the error:
> 
> > make[5]: *** [../../ebin/megaco_flex_scanner_handler.beam] Error 1
> 
> @bjorng I am still seeing this issue with 26. It has not been eliminated and I don't think you should have closed it.

@jdmarshall From your comments in https://github.com/kerl/kerl/issues/514 it seems like you found out what the problem was and everything is working for you now?

**Comment by jdmarshall** [comment] 2024-03-11 20:36
@garazdawi Yes! Make absolutely sure you've scrubbed ErlangInstaller off your machine. They are mutually incompatible.  Check your .rc .profile and .login files. Otherwise you get cryptic error messages.
