### ISSUE TITLE
`os:putenv/2` doesn't set environment, especially TZ

### ISSUE THREAD

**Issue by pguyot** [erlang/otp#7228] opened 2023-05-13 17:12 UTC
**Describe the bug**
It looks like os:putenv/2 doesn't set environment, instead environment is set when forking.

As a result, setting TZ doesn't work as expected.

**To Reproduce**
```
$ erl -noshell -eval 'erlang:display(erlang:localtime())' -s init stop
{{2023,5,13},{19,6,23}}
$  TZ=Europe/London erl -noshell -eval 'erlang:display(erlang:localtime())' -s init stop
{{2023,5,13},{18,6,35}}
$  erl -noshell -eval 'os:putenv("TZ", "Europe/London"), erlang:display(os:cmd("date"))' -s init stop
"Sat May 13 18:06:42 BST 2023\n"
$  erl -noshell -eval 'os:putenv("TZ", "Europe/London"), erlang:display(erlang:localtime())' -s init stop
{{2023,5,13},{19,6,56}}
```

**Expected behavior**
Last call should have displayed:
`{{2023,5,13},{18,6,56}}`

However, we should be able to change timezone by setting TZ. Nif functions would probably also benefit from `os:putenv/2` to actually modify the environment if they don't already (this was not tested).

NB: `erlang:localtime()` behaves properly by calling `tzset(3)`. The problem really seems to be related to `os:putenv/2`.

**Affected versions**
Tested and confirmed on Erlang/OTP 25  and Erlang/OTP 26 RELEASE CANDIDATE 3

**Additional context**
This was tested on macOS.

**Comment by jhogberg** [comment] 2023-05-13 21:21
Thanks for your report, this is by design since OTP 21. Environment variables are inherently thread-unsafe so we’ve replaced them with a thread-safe emulation that’s passed on to spawned processes (and NIFs/drivers that use `enif_getenv`).

If we allowed modifying the regular environment variables like we did in the past, a concurrent call to `os:putenv/1` could run roughshod over the read of `TZ` in `tzset(3)` and crash the emulator or change the result.

If you require this behavior, write a NIF and hope for the best.

**Comment by pguyot** [comment] 2023-05-13 22:32
Thank you for the explanation. While this appears indeed in the release notes of OTP 21 as `OTP-14666`, it probably should be added to the documentation of `os:putenv/2` which wasn't updated, to avoid any surprise.

I guess a special treatment of `TZ` & `TZDIR` with a mutex to avoid any crash in `tzset(3)` might seem expensive, yet it seems like what would be required to safely implement this capability. Even a custom nif can be considered dangerous, as you write it. Interestingly, some libc implementation are safer than what the standard requires. Alternatively, `erlang:localtime/0` would have to parse the local copy of `TZ` and `TZDIR` instead of relying on libc.

**Comment by jhogberg** [comment] 2023-05-14 21:09
It’s documented in the driver/NIF APIs which is the only place where this behavior is observable. That `erlang:localtime/0` uses `tzset` under the hood on some platforms is an implementation detail that we don’t consider observable.

As for trying to make the environment safe through mutexes, that’s what we used to do and it didn’t work. The problems are fundamental to the environment interface and cannot be fixed by us or libc authors (for starters, raw pointers into the environment block are exposed through global symbols. Yay.).

I get the feeling that what you actually want is a way to change the local time zone though, or to query the time in a specific time zone (`erlang:localtime/1` with TZ option?). Would that suffice?

**Comment by okeuday** [comment] 2023-05-14 23:42
@jhogberg Using a local timezone in Erlang, in a long-running system would likely require a way to update an isolated timezone database.  I understand that functionality is likely not being considered or pursued currently, but it seems like this TZ problem can be part of a larger problem.  For C++ dependencies, https://github.com/HowardHinnant/date can be helpful and provide usage of an isolated timezone database.

**Comment by pguyot** [comment] 2023-05-15 06:44
> I get the feeling that what you actually want is a way to change the local time zone though, or to query the time in a specific time zone (`erlang:localtime/1` with TZ option?). Would that suffice?

Based on what you describe, `erlang:localtime/1` would be the cleanest solution.
- Users willing to set the timezone for ports or subcommands would use `os:putenv/2` according to these ports/subcommands semantics.
- Users willing to get the local time for a given timezone would use `erlang:localtime/1`.
- There would be no way to influence calls to `erlang:localtime/0`, especially including in other processes, as opposed to what `os:putenv("TZ", Val)` achieved before OTP-21 and could theoretically yield a crash as `tzset(3)` was not protected by a mutex.

While I agree with @okeuday that this might yield to reimplement handling a full timezone db, this could actually be limited to the semantics of POSIX first two TZ formats (or second format) which do not rely on a database, leaving full database handling to a third party library.

**Comment by jhogberg** [comment] 2023-05-15 09:30
Great, I'll add a ticket to our backlog on investigating `erlang:localtime/1` or similar.

> achieved before OTP-21 and could theoretically yield a crash as tzset(3) was not protected by a mutex.

Not to be snarky, but the crash that triggered the change was all but theoretical, and made it clear that no amount of locking would render things safe in the general case.

**Closed** 2023-05-15 09:31 UTC
Labels: team:VM, not a bug
