### ISSUE TITLE
Distribution handshake error ( Connection attempt from node .. rejected. Invalid challenge reply )

### ISSUE THREAD

**Issue by jovdipp** [erlang/otp#5063] opened 2021-07-20 23:53 UTC
**Describe the bug**
Two nodes with different cookies trying to connect to each other after both nodes have previously 
use set_cookie(OtherNode, OtherCookie)

**To Reproduce**
1. Start two nodes with different cookies.
2. On each node call erlang:set_cookie( Node, Cookie ), replacing Node & Cookie with the Other Nodes details
3. attempt connecting the nodes from either node ( i.e net_adm:ping )
4. Error appears "Connection attempt from node .. rejected. Invalid challenge reply "

**Expected behavior**
I expect the nodes to connect successfully.

**Affected versions**
23.3.3 is what I have tested on

**Additional context**
I created a Pull request with Tests and Fix.
( https://github.com/erlang/otp/pull/5062 )

**Comment by RaimoNiskanen** [comment] 2021-07-30 13:55
I have created an alternative pull request, based on yours, with an alternative fix (that I believe to be correct) and slightly modified test case. PR #5082

**Comment by jovdipp** [comment] 2021-08-04 01:45
> I have created an alternative pull request, based on yours, with an alternative fix (that I believe to be correct) and slightly modified test case. PR #5082

@RaimoNiskanen to keep in sync for others finding the issue, with our comments in PR #5062. 
As you stated the additional PR #5082 created would not be backward compatible.

**Comment by mikpe** [comment] 2021-08-10 11:55
You told both nodes to use the other node's cookie when communicating with that other node. This creates an inconsistent view of which cookie to use for that connection, which causes the rejections.

The correct procedure is to tell _one_ node which cookie to use for the _other_ node, as [documented](https://erlang.org/doc/reference_manual/distributed.html#security).

I don't see a bug here.

**Comment by jovdipp** [comment] 2021-08-10 16:46
@mikpe perhaps read the conversation on the PR #5062 to better your understand the bug.

https://github.com/erlang/otp/pull/5062

Both @RaimoNiskanen and I discuss and breakdown the use cases for communicating to other nodes in detail.

Also reading the documentation link provided states for a node "...connect to, or accept a connection from..." to use set_cookie for the other node. 
it doesn't state this should exclusively or only be done by one node. Which is correct from a general understanding of intent but not correct in terms of the code implementation. 

Due to the allowing connection to or from one node to another, the mechanism shouldn't break simply because both nodes want to allow the other to connect at any time.

**Comment by RaimoNiskanen** [comment] 2021-08-10 19:17
I am more and more inclined to believe that @mikpe and people in my team are right.  This is not a bug.  It is the documentation may need clarification.

The documentation says that both nodes have to use the same cookie when communicating and which cookie that is used is either the default cookie or an explicit cookie for the other node.  The short example also states that calling `erlang:set_cookie(Node2, DiffCookie)` in node 1 is needed (and sufficient) to make the nodes communicating.
All of this is according to the current implementation.

A possible clarification should mention the incorrect configuration of setting node 2's cookie in node 1 _and_ node 1's cookie in node 1 which makes the nodes use different cookies (each others', reversed) for the handshake and therefore fails.

The code in `dist_util.erl` that uses the variable names `MyCookie` and `HisCookie` are confusing borderline a bug, which is what threw me and @jovdipp off track here.

**Comment by jovdipp** [comment] 2021-08-10 21:49
I do not agree. The MyCookie and HisCookie names did not mislead me off track but are part of the understanding of unexpected behaviour. 

It seems irrational that two nodes simply knowing each others cookie **prevents** connecting, even more so now that there is a PR #5062 that corrects the behaviour without changing existing use cases.

Further, both nodes knowing each others cookie is a greater level of "trust" in a general sense, not saying it should be required but simply that is it valid.

**Comment by RaimoNiskanen** [comment] 2021-08-11 08:19
Since the current behaviour is according to documentation (at least not contradicted in any way), we cannot call it a bug.

The only reason, then, to change the current behaviour, would be if it has usability problems.  Your PR #5062 changes the behaviour so that either the dedicated or the default cookie would work, but I see no reason to do that change.  In fact, trying several cookies, I think, should be reserved for a future, unlikely but possible, feature addition to facilitate updating cookies in flight.

**Comment by RaimoNiskanen** [comment] 2021-08-11 09:51
I have created a new PR #5111 with cleanup, clarification, and feature additions.

**Comment by RaimoNiskanen** [comment] 2021-08-18 13:21
PR #5111 has been merged.

Thank you for reporting and investigating this issue.

**Closed by RaimoNiskanen** 2021-08-18 13:21 UTC
Labels: team:VM, in progress, not a bug, priority:medium
