### ISSUE TITLE
[erlc] internal consistency check failed on bif '<': "unassigned"

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6617] opened 2023-01-02 11:55 UTC
On master,
```erlang
f(X) ->
    (try
        (true or garbage_collect()) xor
            is_tuple(catch (1 / 0))
    of
        #{} ->
            ok
    catch
        _ ->
            ok
    end) < X.
```
crashes erlc with the error message:
```
unassigned3:1: function f/1+34:
  Internal consistency check failed - please report this bug.
  Instruction: {bif,'<',{f,0},[{atom,ok},{y,1}],{x,0}}
  Error:       {unassigned,{y,1}}:
```
This might be a duplicate of https://github.com/erlang/otp/issues/6603 and/or https://github.com/erlang/otp/issues/6614, since both show `Error: {unassigned, {y,`. I am filing it separately because it triggers on a different instruction (bif '<' vs move/bs_get_integer2), with rather different testcases, so I am not sure whether it is a duplicate or not.

**Comment by jhogberg** [comment] 2023-01-02 14:48
Thanks for your report, closing this as duplicate of #6603 :)

**Closed by jhogberg** 2023-01-02 14:48 UTC
Labels: team:VM, bug
