### ISSUE TITLE
Erlang driver hasn't been included in libei.a library for MacOS distribution. erl driver creation fails.

### ISSUE THREAD

**Issue by amitabhadatta14** [erlang/otp#8869] opened 2024-09-30 07:59 UTC
Erlang driver hasn't been included in libei.a library for MacOS distribution. erl driver creation fails.

amitabhadatta@VL-MWLGJ26CQ4 c_src % gcc -I /opt/mqm/inc  -I /usr/local/lib/erlang/usr/include  -o mq_series_drv.so mq_series_drv.c -fpic -shared -L /opt/mqm/lib64 -L /usr/local/lib/erlang/lib -L /usr/local/lib/erlang/lib/erl_interface-5.5.1/lib  -lei -lmqic_r -lpthread
ld: Undefined symbols:
  _driver_alloc, referenced from:
      _mq_drv_start in mq_series_drv-1e7a57.o
      _do_connect in mq_series_drv-1e7a57.o
      _do_put in mq_series_drv-1e7a57.o
      _do_get in mq_series_drv-1e7a57.o
      _alloc_and_decode_binary in mq_series_drv-1e7a57.o
      _handle_get in mq_series_drv-1e7a57.o
  _driver_async, referenced from:
      _do_connect in mq_series_drv-1e7a57.o
      _do_put in mq_series_drv-1e7a57.o
      _do_get in mq_series_drv-1e7a57.o
  _driver_free, referenced from:
      _mq_drv_stop in mq_series_drv-1e7a57.o
      _ready_async in mq_series_drv-1e7a57.o
      _ready_async in mq_series_drv-1e7a57.o
      _do_put in mq_series_drv-1e7a57.o
      _do_get in mq_series_drv-1e7a57.o
      _do_free in mq_series_drv-1e7a57.o
      _do_free in mq_series_drv-1e7a57.o
      ...
  _driver_output, referenced from:
      _ready_async in mq_series_drv-1e7a57.o
      _error_bad_arg in mq_series_drv-1e7a57.o
      _return_error in mq_series_drv-1e7a57.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have also tried to build from source code but the problem remains same. 

There is no issues building a erl driver in linux environment with same command as above.

This needs to be investigated and fixed in next release.

**Comment by jhogberg** [comment] 2024-09-30 08:23
Duplicate of #8866

**Closed** 2024-09-30 08:23 UTC
Labels: bug
