### ISSUE TITLE
uri_string:normalize is broken for `.` in the uri

### ISSUE THREAD

**Issue by itssundeep** [erlang/otp#4808] opened 2021-05-06 18:50 UTC
**Describe the bug**
We are noticing that uri_string:normalize is broken for fields with '.' in it. Like for example 
```
uri_string:normalize("http://foo.com?fields=amount%2812%252e00%29").
"http://foo.com/?fields=amount%2812%2e00%29"
```
We are noticing this issue after this change https://github.com/erlang/otp/pull/2793

```
 uri_string:normalize("http://foo.com?fields=amount%2812%252e00%29").
"http://foo.com/?fields=amount%2812%252e00%29"
```

As this api is used in httpc:request, this ends up sending wrong request.

**Expected behavior**
Browser does decode it properly `decodeURIComponent(decodeURIComponent('amount%281%252e00%29')`

**Comment by u3s** [comment] 2021-05-14 11:55
I'm not sure if this actually a bug.
Change #2793 adjusted uri_string:normalize/2 behavior to description found in RFC3986.
It was marked as potentially incompatible in the release notes, so I guess the
author was aware about behavior change.

I would like to relate to RFC3986, including those sections as most relevant:
https://datatracker.ietf.org/doc/html/rfc3986#section-2.3
https://datatracker.ietf.org/doc/html/rfc3986#section-2.4
https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.2

unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"

According to section 6.2.2.2, during Percent-Encoding normalization, only characters from unreserved set should be
decoded.

According to section 2.4, if URI contains %25 then it should be treated as data
rather than indicator for percent-encoded octets.

Additonally, with previous behavior % and %25 were equivalent and always meaning an indicator for percent-encoded octets, so there was no way of sending
% character as data.

Please explain what you mean by 'wrong request' - I would say the that normalized request is equivalent to the input URI.

Please specify what you mean by Expected behavior section.
Multiple decoding of same URI is forbidden by RFC.

**Comment by u3s** [comment] 2021-05-21 09:53
Closing due to inactivity and belief that it is not a bug.

**Closed** 2021-05-21 09:52 UTC
Labels: bug, in progress, team:PS
