### ISSUE TITLE
Strings printed to stdout are hidden by shell

### ISSUE THREAD

**Issue by stolen** [erlang/otp#7263] opened 2023-05-18 14:59 UTC
**Describe the bug**
When printing to stdout (e.g. via `io:format`) output disappears when shell prompt is active.
This also breaks logging to shell (via logger) and some tools like redbug.

**To Reproduce**
```
otp_src_26.0$ bin/erl
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]

Eshell V14.0 (press Ctrl+G to abort, type help(). for help)
1> io:format(standard_io, "hello\n", []).
hello
ok
2> spawn(fun() -> io:format(standard_io, "hello\n", []) end).
hello
<0.89.0>
3> spawn(fun() -> timer:sleep(100), io:format(standard_io, "hello\n", []) end).
<0.91.0>
4>
```
First two commands work as expected (shell is blocked by execution).
Third command prints to stdout when the shell is interactive, and the output disappears.

Same thing happens even with error reports:
```
4> spawn(fun() -> timer:sleep(100), 1=2 end).
<0.93.0>
5> =ERROR REPORT==== 18-May-2023::17:01:56.886729 ===
```
The report is printed, but pressing up or down key leaves only its header visible.

**Expected behavior**
Bytes output to stdout should stay visible.

**Affected versions**
  * 26.0

**Additional context**
It was OK in 26rc3. Seems like an unwanted effect of #7169
  * OK at 8305dd5e2b
  * broken at 16139b6a35 (next commit, merging #7169)

**Comment by mikpe** [comment] 2023-05-19 11:37
I tracked a shell regression with OTP-26.0 in Klarna's main servicing system KRED to the same commit. Upon startup we have a bunch of log output to the same terminal as the shell. Hitting the first Return in the shell erases the log output.

A second nit is that we have long prompts in the shell, on the form "${user}@kred-${cluster}-${name}". When an input line is incomplete, say simply by hitting return, the OTP-26.0 shell insists on indenting to the full length of the prompt and then print "..". This is waste of screen estate. I'd prefer if it didn't indent at all.

**Comment by isvilen** [comment] 2023-05-21 14:48
Probably the same problem is causing issues when using tab-completion in custom SSH shell.
I have a function for tab-completion set with `io:setopts({expand_fun, expand_fun()})` and the list of possible expansions is not displayed. Works fine at commit 8305dd5, doesn't work at 16139b6.

**Comment by ferd** [comment] 2023-05-25 15:38
https://github.com/ferd/recon/issues/105 seems related to this as well.

**Comment by frazze-jobb** [comment] 2023-05-26 08:24
Thanks for reporting I will look into it ASAP

**Comment by frazze-jobb** [comment] 2023-05-29 08:34
> I tracked a shell regression with OTP-26.0 in Klarna's main servicing system KRED to the same commit. Upon startup we have a bunch of log output to the same terminal as the shell. Hitting the first Return in the shell erases the log output.
> 
> A second nit is that we have long prompts in the shell, on the form "${user}@kred-${cluster}-${name}". When an input line is incomplete, say simply by hitting return, the OTP-26.0 shell insists on indenting to the full length of the prompt and then print "..". This is waste of screen estate. I'd prefer if it didn't indent at all.

How it worked before is that it would print "${user}@kred-${cluster}-${name}" instead of "       .. " am I right, so its not indenting more than before? 
I will remove the extra indent and only print ".. " for now.
I would prefer no prefix at all, to make it easy to copy and paste, but it would not be clear whether the evaluation is still processing or if the prompt is unfinished.

Regarding the regression you found, do you have something that I can use to replicate it? I have a fix for this issue, not certain you have the same issue.

**Comment by frazze-jobb** [comment] 2023-05-29 08:37
> Probably the same problem is causing issues when using tab-completion in custom SSH shell. I have a function for tab-completion set with `io:setopts({expand_fun, expand_fun()})` and the list of possible expansions is not displayed. Works fine at commit [8305dd5](https://github.com/erlang/otp/commit/8305dd5e2b962ada3403a6fc0c600367afdfec5e), doesn't work at [16139b6](https://github.com/erlang/otp/commit/16139b6a35944583b4f1ef05c7698bfe2f771c7a).

Could you provide steps to reproduce this?

**Comment by frazze-jobb** [comment] 2023-05-29 11:35
@isvilen in that case I think its working as intended, expansions are displayed after the prompt and does not produce a new prompt. unless there are too many expansion results to display.

**Comment by isvilen** [comment] 2023-05-29 12:05
> @isvilen in that case I think its working as intended, expansions are displayed after the prompt and does not produce a new prompt. unless there are too many expansion results to display.

@frazze-jobb in this example the difference in behaviour of `otp-26` and previous versions in not significant, but if you trying to expand parameters of a command it becomes a problem:
If there is `cmd1` with possible parameters `p1` and `p2` and current line is `> cmd1` after `TAB` is pressed `p1` and `p2` are offered as completions and user types `p1` `ENTER` . In this case `io:getline`  from versions before `otp-26.0` returns `cmd1 p1` which is valid command, but now it will return only `p1` which is not.

**Comment by frazze-jobb** [comment] 2023-05-29 12:06
@isvilen, thanks! I'll take a look

**Comment by mikpe** [comment] 2023-05-29 14:51
> @mikpe How it worked before is that it would print "${user}@kred-${cluster}-${name}" instead of " .. " am I right, so its not indenting more than before? I will remove the extra indent and only print ".. " for now. I would prefer no prefix at all, to make it easy to copy and paste, but it would not be clear whether the evaluation is still processing or if the prompt is unfinished.

Yes, it would print the prompt again. Just double-checked with OTP-24.
The OTP-26 behaviour of indenting with this massive space threw me.

> Regarding the regression you found, do you have something that I can use to replicate it? I have a fix for this issue, not certain you have the same issue.

Sorry, it's in our proprietary code base. I can test proposed fixes easily enough though.

**Comment by frazze-jobb** [comment] 2023-05-30 07:08
@isvilen, I see that I have missed to implement multiline editing functionality for ssh_cli, I'm working on it, will track it in #7318

**Closed** 2023-06-20 09:30 UTC
Labels: team:VM, bug
