### ISSUE TITLE
Overrun stack and heap OTP-26.0

### ISSUE THREAD

**Issue by vshev4enko** [erlang/otp#7292] opened 2023-05-24 14:06 UTC
**Describe the bug**
Application down few seconds after the run release in AWS eks

**To Reproduce**
Unfortunately i have no idea how to reproduce.

**Affected versions**
26.0

**Additional context**
AWS EKS
erlang 26.0
alpine 3.18.0

Application logs
```
hend=0x00007f4f6f34c7f0
stop=0x00007f4f6f34c670
htop=0x00007f4f6f34c678
heap=0x00007f4f6f349600
beam/erl_gc.c, line 735: <0.3141.0>: Overrun stack and heap
```

**Comment by benoawfu** [comment] 2023-05-31 08:00
Same thing here, alpine 3.18.0, OTP 26.0 but on AWS ECS Fargate.

```
hend=0x00007f5329e030c8
stop=0x00007f5329e02db8
htop=0x00007f5329e02dc0
heap=0x00007f5329df5d28
beam/erl_gc.c, line 735: <0.190015.0>: Overrun stack and heap
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
```

**Comment by jhogberg** [comment] 2023-05-31 08:19
Thanks for your report, could you provide a core dump together with the `beam.smp` binary?

**Comment by benoawfu** [comment] 2023-05-31 08:29
Sorry I can't retrieve that off ECS.

**Comment by jhogberg** [comment] 2023-05-31 08:36
That's unfortunate :-/

Can you reproduce this with image that isn't based on alpine (or more importantly, doesn't use `musl`)?

**Comment by benoawfu** [comment] 2023-05-31 08:47
It's production stuff, sorry I can't do experiments on this. I haven't had any issue on the pre-production/test servers.

**Comment by jhogberg** [comment] 2023-05-31 09:25
`musl` makes the JIT to run in a weird configuration that isn't as well-tested as the one under `GNU libc`, so it would be nice if you could try it out some time. If it only happens under `musl` it'll be much easier for me to narrow things down.

As an added bonus you'll get 10-15% better performance on linear code. :-)

**Comment by vshev4enko** [comment] 2023-06-01 08:49
you mean run the same application under ubuntu instead alpine?

**Comment by jhogberg** [comment] 2023-06-01 11:28
Yeah, that'd work. As long as the environment uses `GNU libc` instead of `musl`.

**Comment by vshev4enko** [comment] 2023-06-01 13:38
Replaced base image with `debian-bullseye-20230227-slim` and it works. I can't about performance but no crashes.

**Comment by jhogberg** [comment] 2023-06-01 13:53
Thank you, then the crash may be related to that configuration. If you can provide a core dump (+`beam.smp`) the next time this crashes we'd be very thankful.

**Comment by wkirschbaum** [comment] 2023-06-20 22:39
@jhogberg would you recommend as a general rule that we avoid musl for running erlang in production? 

I am getting the same issue on alpine:
```
hend=0x00007f0a7e8fd830
stop=0x00007f0a7e8fd630
htop=0x00007f0a7e8fd638
heap=0x00007f0a7e8f0490
beam/erl_gc.c, line 735: <0.2688.0>: Overrun stack and heap
```

And can reproduce it on a build server. I don't see a  `erl_crash.dump` file, so if someone can maybe help me get the dump and beam.smp files I can post it.

**Comment by jhogberg** [comment] 2023-06-21 07:49
> @jhogberg would you recommend as a general rule that we avoid musl for running erlang in production?

I'd avoid it for now, this only seems to happen with this configuration.

> And can reproduce it on a build server. I don't see a erl_crash.dump file, so if someone can maybe help me get the dump and beam.smp files I can post it.

That's great! It ought to have dumped core and not generated a crash dump, so that's why you're not seeing one. Please send us the core dump together with `beam.smp` if you can. :-)

**Comment by wkirschbaum** [comment] 2023-06-21 11:50
@jhogberg beam.smp and core dump: https://git.sr.ht/~whk/erlang-26-crash-reports/tree

Please let me know if there is anything which will help.

**Comment by jhogberg** [comment] 2023-06-21 16:32
That `beam.smp` is stripped, do you happen to have the symbols saved somewhere?

**Comment by wkirschbaum** [comment] 2023-06-21 16:35
@jhogberg i can't even pretend to understand what you mean, since I have very little erlang or gdb experience. If its somewhere on the instance I can upload it, but not sure where to look.

**Comment by wkirschbaum** [comment] 2023-06-21 16:47
I just copied what was in this container, but have a feeling its not there: hexpm/elixir:1.15.0-erlang-26.0.1-alpine-3.18.2 
```
cp /usr/local/lib/erlang/erts-14.0.1/bin/beam.smp build-archive
```

**Comment by jhogberg** [comment] 2023-06-26 07:40
That's really annoying, digging into the images they seem based on https://hub.docker.com/_/erlang which forcibly strips all symbols without having the common decency to save them anywhere. It would've been nice if they didn't strip them in that layer but left it to the final one.

We're basically stuck until we have the symbols, I'll try to get in touch with the folks maintaining those images but I'm not sure how long that will take. In the meantime I suppose we can make our own nearly-identical images by removing the lines that strip symbols ([the ones that look like this](https://github.com/erlang/docker-erlang-otp/blob/91311b4b6e25a98416f87f77004361ce7439fece/26/alpine/Dockerfile#L44)), but if you want to wait until the upstream images contain symbols I'm fine with that.

**Comment by wkirschbaum** [comment] 2023-06-26 07:59
@jhogberg thanks for having a look. I can try the suggested change on our build server somewhere this week and will post. There is no urgency for me, but sure more people will run into this soon.

**Comment by princemaple** [comment] 2023-07-06 11:18
Probably worthless information but here it is anyway: it seems to only happen on apps that use large chunks of memory. Out of 3 apps that I'm running with OTP 26 on alpine, only one that uses large chunk of memory had issues and crashed multiple times a day. The other 2 had been running fairly smoothly.

**Comment by mudssrali** [comment] 2023-07-20 12:29
> Probably worthless information but here it is anyway: it seems to only happen on apps that use large chunks of memory. Out of 3 apps that I'm running with OTP 26 on alpine, only one that uses large chunk of memory had issues and crashed multiple times a day. The other 2 had been running fairly smoothly.

I don't think so it's memory issue -- I've 16GB machine on cloud and locally -- works fine on local however deployment on cloud is crashing -- fairly simple Elixir application that runs bunch of GenServers -- with 1MB payload. I'm using alpine -- guessing by default wiith OTP-26
```
FROM elixir:1.15.1-alpine
```
Error
```
hend=0x00007fdd10cc0e18
stop=0x00007fdd10cc0db8
htop=0x00007fdd10cc0dc0
heap=0x00007fdd10cc0258
beam/erl_gc.c, line 735: <0.1616.0>: Overrun stack and heap
```
Previously the same application was working fine on `elixir:1-8-alpine`

**Comment by Lankester** [comment] 2023-08-02 23:34
I have just got this error in a Debian docker container running off of the `elixir:1.15-slim` Dockerfile.

```
user@host:/app# cat /etc/issue
Debian GNU/Linux 11 \n \l
```

Error:

```
hend=0x00007fb33de2c288
stop=0x00007fb33de2c080
htop=0x00007fb33de2c088
heap=0x00007fb33de2b6c8
beam/erl_gc.c, line 735: <0.253.0>: Overrun stack and heap
Aborted (core dumped)
```

It's a relatively simple application consisting of 3 GenServers.

I have a core dump but can't share due to sensitive information within and I have been unable to replicate the issue in a test app that omits the sensitive info.

I've attached a gdb backtrace in case that's useful though and I am open to suggestions and happy to help further.

[backtrace.txt](https://github.com/erlang/otp/files/12245461/backtrace.txt)

**Comment by garazdawi** [comment] 2023-08-03 05:45
If you can source [etp-commands](https://github.com/erlang/otp/blob/master/erts/etc/unix/etp-commands.in) and then run `etp-processes` and `etp-stacktrace p` that would be a great start.

Since the error happens in the GC, it could be that whatever triggered the error is long gone, but we may get lucky.

```
(gdb) source etp-commands.in
(gdb) etp-processes
(gdb) frame 5
(gdb) etp-stacktrace p
```

**Comment by Lankester** [comment] 2023-08-03 10:05
Done, gdb log attached.

[gdb.txt](https://github.com/erlang/otp/files/12249510/gdb.txt)

**Comment by garazdawi** [comment] 2023-08-03 10:36
Thanks! If you get any more crashes, please do the same so that we can compare them.

What version of `Mint.Websocket` are you running?

And to everyone else here, are you also running `Mint.Websocket`?

**Comment by vshev4enko** [comment] 2023-08-03 11:40
I am not running `Mint.Websocket`. 
Also i stopped getting this error after switching the image from alpine to debian.

**Comment by Lankester** [comment] 2023-08-03 11:51
It seems to crash almost every time in the same place — receiving and decoding a websocket message. Also, possibly worth pointing out hardware is Intel Mac.

`Mint` is version 1.5.1.

Another gdb log attached from another crash.

[gdb_crash_2.txt](https://github.com/erlang/otp/files/12250445/gdb_crash_2.txt)

**Comment by Lankester** [comment] 2023-08-03 15:34
Moving to OTP 25 via `elixir:1.15-otp-25-slim` seems to have resolved the issue for me, no further crashes so far.

**Comment by nathany-copia** [comment] 2023-08-03 21:15
Seeing this on OTP 26.0.2 and Alpine 3.17.4

We're using this Docker image -- `hexpm/elixir:1.15.4-erlang-26.0.2-alpine-3.17.4` for the build and running under `alpine:3.17.4` with Erlang bundled via `mix releases`. 

Not sure if the core dump will have symbols in this case (unlike the official Erlang images), or where to find the core.dump, but I'll follow up if we find it.

```
htop=0x00007fe486d4ad48
stop=0x00007fe486d4ad40
heap=0x00007fe486d47ba8
beam/erl_gc.c, line 735: <0.8138.0>: Overrun stack and heap
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
Aborted (core dumped)
```

**Comment by akoutmos** [comment] 2023-08-11 03:36
I am seeing this issue too. I am also running the `hexpm/elixir:1.15.4-erlang-26.0.2-alpine-3.17.4` image and have a mix release Phoenix app running in the container. The only thing that I can correlate this too without much of a deep dive was that this happened right after our app was DoS attacked.

![image](https://github.com/erlang/otp/assets/4753634/e344ae6b-dfbf-418b-98b7-15ece7bbdc2a)

I will try and get more information around this, but for now will revert to `hexpm/elixir:1.15.4-erlang-25.3.2.5-alpine-3.17.4`.

**Comment by bernardo-martinez** [comment] 2023-08-11 10:58
I am seeing this issue too:
```
hend=0x00007ff8c845fb90
stop=0x00007ff8c845fa60
htop=0x00007ff8c845fa68
heap=0x00007ff8c845c9a0
beam/erl_gc.c, line 735: <0.67[52](https://gitlab.otters.xyz/product/business/experience/app/-/jobs/12068617#L52).0>: Overrun stack and heap
```

building image myself with: `elixir 1.15.3` and `erlang 26.0.2`
 running on a gitlab alpine image

**Comment by sverker** [comment] 2023-08-17 09:23
It seems a lot of people are able to reproduce this.
It would be really helpful if someone could give detailed instructions of how to reproduce the crash. Preferably a "minimal" example that is easy as quick to run.

**Comment by ggalan87** [comment] 2023-08-17 10:28
I reached this issue after some rabbitmq server crashes. 

**Setup:** plain LXC container, alpine 1.18 image, erlang-26.0.2, elixir-1.15.4

**Log:**

```
  Starting broker... completed with 5 plugins.      
                                                                                                         
hend=0x00007fe234eb34b0                                                                                  
stop=0x00007fe234eb3458                                                                                  
htop=0x00007fe234eb3460                                                                                                                                                                                            
heap=0x00007fe234eb21a0                                                                                  
beam/erl_gc.c, line 735: <0.15407.0>: Overrun stack and heap                                             
Aborted (core dumped)                                                       
```

**Comment by JamesLavin** [comment] 2023-08-17 14:38
In case my context might help anyone debug this, I hit this bug hard yesterday after building (on Apple Silicon) Ubuntu images (plural because I used a variety of base images with various versions of Elixir & Erlang, hoping that one of them might work) to run an Elixir script. Was able to build the images fine, but when I booted the container and ran my .exs file, `Mix.install` never managed to compile the Jason library (https://github.com/michalmuskala/jason). It always blew up with this error message during Jason library compilation.

(Compiling on Apple Silicon adds a layer of complexity, see: https://pythonspeed.com/articles/docker-build-problems-mac/, but this may be a red herring, given that others seem to have hit this issue elsewhere.)

**Comment by ramyma** [comment] 2023-08-18 17:21
> It seems a lot of people are able to reproduce this. It would be really helpful if someone could give detailed instructions of how to reproduce the crash. Preferably a "minimal" example that is easy and quick to run.

I created a simple repo where I'm able to reproduce the issue consistently: https://github.com/ramyma/otp_crash

You'll just have to run  `iex -S mix phx.server`, and within a couple of minutes it will crash with:
```
=0x00007f83a6f2b2a0
hea[info] Received and echoing back
iex(1)> 7f83a6f281c0
beam/erl_gc.c, line 735
iex(1)>  Overrun stack and heap
[info] Received and echoing back
iex(1)> [1]    95162 IOT instruction (core dumped)  iex -S mix phx.server
```

**Comment by sverker** [comment] 2023-08-21 11:54
Thanks, @ramyma and @Lankester for the "crash repos".

@ramyma Just to be clear; you ran it directly on Ubuntu without any docker image?

**Comment by ramyma** [comment] 2023-08-21 12:12
> Thanks, @ramyma and @Lankester for the "crash repos".
> 
> @ramyma Just to be clear; you ran it directly on Ubuntu without any docker image?

@sverker yes, directly on Ubuntu.

**Closed** 2023-08-25 06:07 UTC
Labels: team:VM, bug
