### ISSUE TITLE
Legacy ciphers set via`ciphers` option for `ssl:connect` ignored in OTP 24

### ISSUE THREAD

**Issue by samwar** [erlang/otp#5624] opened 2022-01-19 21:37 UTC
**Describe the bug**
Legacy ciphers passed along via the `ciphers` option to `ssl:connect` appear to be ignored when making the client hello in OTP 24. In versions prior to OTP 24, these ciphers are passed along in the list of suites used to make the handshake. It appears in OTP 24, they can be added to the `ciphers` option list, but when it comes to the handshake, they are mysteriously absent.  See the `Additional Context` section for `tcpdump` snippet containing the ciphers OTP 23 and 24 used in the client hello.

**To Reproduce**
* Make an SSL connection to a host using only a legacy cipher and record the interaction via `tcpdump`
```erlang
Host = "1.2.3.4",
Cipher = [#{cipher => '3des_ede_cbc',key_exchange => rsa,mac => sha,prf => default_prf}],
ssl:connect(Host, 443,  [{ciphers, Cipher}], timer:seconds(15)).
```
```bash
sudo tcpdump -i <interface_name> -w <file_to_write_the_tcpdump> host 1.2.3.4
```
* Run that piece of code compiled and running in OTP 23 and then in OTP 24.
* Use Wireshark to inspect the `tcpdump` output and compare what cipher suites are used in each client hello

**Expected behavior**
When passing along a legacy cipher to be used by the `ssl:connect`, I would expect it to actually be used in the handshake.

**Affected versions**
OTP 24.x

**Additional context**
Wireshark inspection of the TCP dump when trying to connect with OTP 23.
```
Transport Layer Security
  TLSv1.2 Record Layer: Handshake Protocol: Client Hello
      Content Type: Handshake (22)
      Version: TLS 1.2 (0x0303)
      Length: 98
      Handshake Protocol: Client Hello
          Handshake Type: Client Hello (1)
          Length: 94
          Version: TLS 1.2 (0x0303)
          Random: 61e851c7a8c7416b278d557f50adbb77d3f47a5b924bfc6c0215b9df496a4d6c
          Session ID Length: 0
          Cipher Suites Length: 4
          Cipher Suites (2 suites)
              Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
              Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
          Compression Methods Length: 1
          Compression Methods (1 method)
          Extensions Length: 49
          Extension: server_name (len=17)
          Extension: signature_algorithms (len=24)
          [JA3 Fullstring: 771,255-10,0-13,,]
          [JA3: 05a16d5cfa4f646ecc3497eb698c7276]
```
The same piece of code making the connection using OTP 24. Notice the complete absence of `TLS_RSA_WITH_3DES_EDE_CBC_SHA` and the addition of 40 other suites not passed along in the option.
```
Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 196
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 192
            Version: TLS 1.2 (0x0303)
            Random: 61e8361405acdf2683314651be9b61d0a41eabd9b2a096caaccdcc6a0c269c86
            Session ID Length: 0
            Cipher Suites Length: 82
            Cipher Suites (41 suites)
                Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CCM (0xc0ad)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8 (0xc0af)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CCM (0xc0ac)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 (0xc0ae)
                Cipher Suite: TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02e)
                Cipher Suite: TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 (0xc032)
                Cipher Suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 (0xc026)
                Cipher Suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 (0xc02a)
                Cipher Suite: TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02d)
                Cipher Suite: TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 (0xc031)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
                Cipher Suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 (0xc025)
                Cipher Suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 (0xc029)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 (0x00a3)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x006b)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x006a)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 (0x00a2)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x0067)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x0040)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
                Cipher Suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA (0xc005)
                Cipher Suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA (0xc00f)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
                Cipher Suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA (0xc004)
                Cipher Suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA (0xc00e)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x0038)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x0032)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 69
            Extension: server_name (len=17)
            Extension: signature_algorithms (len=24)
            Extension: supported_groups (len=10)
            Extension: ec_point_formats (len=2)
            [JA3 Fullstring [truncated]: 771,255-49196-49200-49325-49327-49188-49192-49195-49199-49324-49326-49198-49202-49190-49194-49197-49201-49187-49191-49189-49193-159-163-107-106-158-162-103-64-49162-49172-49157-49167-49161-49171-49156-49166-57-]
            [JA3: 1a94ecf73a3bdfef202a3dad73c8d49e]
```

**Comment by IngelaAndin** [comment] 2022-01-20 09:40
This legacy cipher suite is special in the way that it is only supported for TLS versions TLS-1.1 and TLS-1.0.  So what you see is that the cipher suites fall back to the default value.  
```
Erlang/OTP 24 [erts-12.2] [source-3ff726cd11] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Eshell V12.2  (abort with ^G)
1> ssl:start().
ok
2>  Cipher = [#{cipher => '3des_ede_cbc',key_exchange => rsa,mac => sha,prf => default_prf}].
[#{cipher => '3des_ede_cbc',key_exchange => rsa,mac => sha,
   prf => default_prf}]
3>  ssl:connect(localhost, 9999,  [{ciphers, Cipher},{log_level, debug}, {versions, ['tlsv1.1']}])
3> .
=WARNING REPORT==== 20-Jan-2022::10:30:33.112431 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

>>> TLS 1.1 Handshake, ClientHello
[{client_version,{3,2}},
 {random,<<97,233,43,185,111,216,89,204,182,149,113,235,21,218,204,136,244,44,
           255,131,146,125,168,240,171,182,95,47,35,85,41,200>>},
 {session_id,<<>>},
 {cookie,undefined},
 {cipher_suites,["TLS_EMPTY_RENEGOTIATION_INFO_SCSV",
                 "TLS_RSA_WITH_3DES_EDE_CBC_SHA"]},
 
```

Another legacy suite
```
1> ssl:start().
ok
2> Cipher = [#{cipher => aes_128_cbc,key_exchange => rsa,mac => sha, prf => default_prf}].
[#{cipher => aes_128_cbc,key_exchange => rsa,mac => sha,
   prf => default_prf}]
3>  ssl:connect(localhost, 9999,  [{ciphers, Cipher},{log_level, debug}]).
=WARNING REPORT==== 20-Jan-2022::10:38:04.289357 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

>>> TLS 1.3 Handshake, ClientHello
[{client_version,{3,3}},
 {random,
     <<158,219,248,17,151,97,12,2,245,86,8,63,252,16,7,172,162,33,124,91,47,
       52,136,182,134,12,4,3,7,234,143,49>>},
 {session_id,<<>>},
 {cookie,undefined},
 {cipher_suites,
     ["TLS_EMPTY_RENEGOTIATION_INFO_SCSV","TLS_RSA_WITH_AES_128_CBC_SHA"]},

```

**Comment by samwar** [comment] 2022-01-20 15:22
I can assure you this does not work with the `'3des_ede_cbc'` cipher, which seems like a bug to me.
```bash
1> ssl:start().
ok
2> Cipher = [#{cipher => '3des_ede_cbc',key_exchange => rsa,mac => sha,prf => default_prf}],
2> ssl:connect("10.17.25.108", 443,  [{ciphers, Cipher},{log_level, debug}]).
=WARNING REPORT==== 20-Jan-2022::15:22:22.103080 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

>>> TLS 1.2 Handshake, ClientHello
[{client_version,{3,3}},
 {random,<<97,233,126,46,225,93,178,186,160,253,122,167,8,181,206,93,95,237,
           28,0,151,159,241,35,140,53,199,20,94,21,209,152>>},
 {session_id,<<>>},
 {cookie,undefined},
 {cipher_suites,["TLS_EMPTY_RENEGOTIATION_INFO_SCSV",
                 "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
                 "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                 "TLS_ECDHE_ECDSA_WITH_AES_256_CCM",
                 "TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8",
                 "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
                 "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
                 "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                 "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                 "TLS_ECDHE_ECDSA_WITH_AES_128_CCM",
                 "TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8",
                 "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384",
                 "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384",
                 "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384",
                 "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384",
                 "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256",
                 "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256",
                 "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
                 "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
                 "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256",
                 "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256",
                 "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
                 "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384",
                 "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256",
                 "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256",
                 "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
                 "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256",
                 "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",
                 "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256",
                 "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
                 "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
                 "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA",
                 "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA",
                 "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
                 "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
                 "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA",
                 "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA",
                 "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
                 "TLS_DHE_DSS_WITH_AES_256_CBC_SHA",
                 "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
                 "TLS_DHE_DSS_WITH_AES_128_CBC_SHA"]},
 {compression_methods,[0]},
 {extensions,#{alpn => undefined,
               ec_point_formats => {ec_point_formats,[0]},
               elliptic_curves =>
                   {elliptic_curves,[{1,3,132,0,35},
                                     {1,3,132,0,34},
                                     {1,3,132,0,10},
                                     {1,2,840,10045,3,1,7}]},
               max_frag_enum => undefined,
               next_protocol_negotiation => undefined,
               renegotiation_info => {renegotiation_info,undefined},
               signature_algs =>
                   {hash_sign_algos,[{sha512,ecdsa},
                                     {sha512,rsa},
                                     {sha384,ecdsa},
                                     {sha384,rsa},
                                     {sha256,ecdsa},
                                     {sha256,rsa},
                                     {sha224,ecdsa},
                                     {sha224,rsa},
                                     {sha,ecdsa},
                                     {sha,rsa},
                                     {sha,dsa}]},
               signature_algs_cert => undefined,
               sni => {sni,"10.17.25.108"},
               srp => undefined}}]
writing (201 bytes) TLS 1.2 Record Protocol, handshake
0000 - 16 03 03 00 c4 01 00 00  c0 03 03 61 e9 7e 2e e1    ...........a.~..
0010 - 5d b2 ba a0 fd 7a a7 08  b5 ce 5d 5f ed 1c 00 97    ]....z....]_....
0020 - 9f f1 23 8c 35 c7 14 5e  15 d1 98 00 00 52 00 ff    ..#.5..^.....R..
0030 - c0 2c c0 30 c0 ad c0 af  c0 24 c0 28 c0 2b c0 2f    .,.0.....$.(.+./
0040 - c0 ac c0 ae c0 2e c0 32  c0 26 c0 2a c0 2d c0 31    .......2.&.*.-.1
0050 - c0 23 c0 27 c0 25 c0 29  00 9f 00 a3 00 6b 00 6a    .#.'.%.).....k.j
0060 - 00 9e 00 a2 00 67 00 40  c0 0a c0 14 c0 05 c0 0f    .....g.@........
0070 - c0 09 c0 13 c0 04 c0 0e  00 39 00 38 00 33 00 32    .........9.8.3.2
0080 - 01 00 00 45 00 00 00 11  00 0f 00 00 0c 31 30 2e    ...E.........10.
0090 - 31 37 2e 32 35 2e 31 30  38 00 0d 00 18 00 16 06    17.25.108.......
00a0 - 03 06 01 05 03 05 01 04  03 04 01 03 03 03 01 02    ................
00b0 - 03 02 01 02 02 00 0a 00  0a 00 08 00 19 00 18 00    ................
00c0 - 16 00 17 00 0b 00 02 01  00                         .........
{error,closed}
3>
```

**Comment by IngelaAndin** [comment] 2022-01-20 16:14
Well, I will look into it some more! The thing is that this specific cipher suite is explicitly removed for TLS-1.2 (although I last touched that line of code it was not when it was introduced). As it was explicitly removed I assumed it was on purpose and as it is mandatory in TLS-1.1 it makes sense it should work there even support was dropped in TLS-1.2. However, I did not yet find the exact reason this is so.

**Comment by zzantozz** [comment] 2022-01-20 16:30
> So what you see is that the cipher suites fall back to the default value.

This seems like very surprising behavior. When you pass something to a function, the function should act on those arguments or else signal that they're invalid. A function that silently ignores its arguments and does something else is only going to cause confusion.

**Comment by samwar** [comment] 2022-01-20 17:59
I'm not entirely sure, but I think [this is where the change](https://github.com/erlang/otp/commit/7f533c862951efc2072d2738362241f2411e1ebc#diff-c6e4e01fbddfaa6057fc43144940a337eb3db17891c62cce9ad2123e0107f776L2586) was introduced that removes the cipher from the list. Maybe it can be modified to not filter out ciphers passed in via the options list?

**Comment by IngelaAndin** [comment] 2022-01-21 08:40
> I'm not entirely sure, but I think [this is where the change](https://github.com/erlang/otp/commit/7f533c862951efc2072d2738362241f2411e1ebc#diff-c6e4e01fbddfaa6057fc43144940a337eb3db17891c62cce9ad2123e0107f776L2586) was introduced that removes the cipher from the list. Maybe it can be modified to not filter out ciphers passed in via the options list?

No that is not the change.  I however did find the commit introducing the change. 7f533c862951efc2072d2738362241f2411e1ebc (which happens to be mine too)

The problem is here where this cipher suite is explicitly removed from TLS-1.2
```
rsa_suites({3, 3}) ->
    rsa_suites_exclusive(3) -- [?TLS_RSA_WITH_3DES_EDE_CBC_SHA];
```

Now I do not see that the change I implemented here motivates this, so I change my mind that this is a bug. Just removing  ` -- [?TLS_RSA_WITH_3DES_EDE_CBC_SHA]` will
make your configuration work. It will also not be included in the default value. I honestly can not remember why I made that change, probably it was an oversight when juggling all cipher suites filterings.

**Comment by IngelaAndin** [comment] 2022-01-21 08:48
> > So what you see is that the cipher suites fall back to the default value.
> 
> This seems like very surprising behavior. When you pass something to a function, the function should act on those arguments or else signal that they're invalid. A function that silently ignores its arguments and does something else is only going to cause confusion.

Well, it only falls back if you provide a correct ciphers suite list that becomes empty when filtering it for run-time support. Correct cipher suites could be filtered out due to the cryptolib that the crypto application is linked to. We did think of maybe changing that but it would not be backward compatible so we documented it instead.

**Comment by IngelaAndin** [comment] 2022-01-22 08:28
#5628 merged

**Closed by IngelaAndin** 2022-01-22 08:28 UTC
Labels: team:PS, bug

**Comment by samwar** [comment] 2022-01-24 22:35
@IngelaAndin any idea when this fix will make it into a release?

**Comment by IngelaAndin** [comment] 2022-01-25 07:35
Well yes, I have piggybacked it on the upcoming patch release OTP-24.2.1 that should be out fairly soon.
