### ISSUE TITLE
ERL-1397: Windows 2016 Server opt_win64_23.1 & 23.0 bin directory missing

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4411] opened 2020-11-02 20:41 UTC
Original reporter: `JIRAUSER16911`
Affected versions: `OTP-23.0`, `OTP-23.1`
Component: `Not Specified`
Migrated from: https://bugs.erlang.org/browse/ERL-1397

---

```
We have lost a day trying to work out why we are getting this issue.  To the point out of *PRUE FRUSTRATION*, we setup an user account, just so we can raise this ticket. 

We don't expect a reply, this is what we did:
 * We wanted to install Erlang onto several Windows 2016 Server machines, to build a RabbitMQ cluster based on 3 servers. 
 * All servers had the latest updates and patches, installed before Erlang was installed. 
 * We have tried install Erlang onto 3 servers, of which 1 server have an Erlang upgraded and the other 2 server with no previous installation of Erlang.
 * We first uninstalled, rebooted and installed Erlang 23.0 onto the server, which had a previous installation of Erlang. 
 * *ISSUE*:  The bin directory *C:\Program Files\erl-23.0\bin*, just would not install, which ever version we tried.
 * We tried to install onto the 2 new Windows 2016 Servers, which had no previous installation of erlang.  The same happened again, and again, and again.
 * Rebooted all 3 server, many, many times.

Trawling through various internet sites and our past knowledge, we did the following:
 * Cleared out any Erlang directory entries we could find in *Program Files* directory.
 * Cleared all references from the windows registry:
 ** *HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson*
 ** *Delete the Folder HKEY_LOCAL_MACHINE\SOFTWARE\Ericsson\Erlang*
 * Removed all *.erlang.cookie* from all users and windows directories.

We had the same issue for version 22.0 and 23.0 ALL EXTRACTLY THE SAME NO BIN DIRECTORY.  We downloaded many times and we used:
 * otp_win64_23.1.exe
 * otp_win64_23.0.exe
 * otp_win64_22.3.exe
 * and my personal favourite otp_win64_22.2.exe 

We believe there is a bug within the uninstall and installation application that is leaving an entry or trace Erlang element somewhere stopping the installation of the bin directory.

You will be glad to know by some minor miracle in the small hours, we have finally installed Erlang 23.1 on 1 server, *with the bin directory*.  We installed Erlang onto the remain 2 servers and copied the bin directory across.  We now has a working RabbitMQ cluster, a day later than scheduled.

Our next scheduled maintenance is Spring'21, please could you investigate and deploy any fixes.

Thank you

 
```

**Comment by dgud** [comment] 2021-02-23 13:30
I'm closing this, we can't reproduce and have not gotten any feedback from you.

**Closed by dgud** 2021-02-23 13:30 UTC
Labels: bug, priority:medium, team:PS, waiting
