### ISSUE TITLE
dialyzer doesn't check type of tuple arguments in function return

### ISSUE THREAD

**Issue by Polexy** [erlang/otp#6383] opened 2022-10-21 12:25 UTC
**Describe the bug**
Dialyzer doesn't check type of tuple arguments in function return.
Example:
By function spec -  it gets type1() and return tuple {get, type2()}
But in real - function gets type1() and return tuple {get, type3()}
type2 != type3
So dialyzer don't raise warning\error

**To Reproduce**
```
-module(foo).

-export([test/0, test_fun/1]).

-spec test_fun(binary()) -> {get, atom()}.
test_fun(M) ->
    {get, M}.

test() ->
    test_fun(<<"foo">>).
```
Result:
```
./rebar3 dialyzer && echo Success || echo Failed
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling foo
===> Dialyzer starting, this may take a while...
===> Add debug_info to compiler options (erl_opts) if Dialyzer fails to load Core Erlang.
===> Updating plt...
===> Resolving files...
===> Checking 206 files in _build/default/rebar3_25.1.1_plt...
===> Doing success typing analysis...
===> Resolving files...
===> Analyzing 1 files with _build/default/rebar3_25.1.1_plt...
Success
```
the same(no dialyzer warn) when calling from another module, example : `foo:test_fun(<<"foo">>).`

**Expected behavior**
Dialyzer warn\error

i also found some behaviour that it's somehow related with export. When we don't export `test_fun` dialyzer raise warning
```
-module(foo).

-export([test/0]).

-spec test_fun(binary()) -> {get, atom()}.
test_fun(M) ->
    {get, M}.

test() ->
    test_fun(<<"foo">>).
```
```
./rebar3 dialyzer && echo Success || echo Failed
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling foo
===> Dialyzer starting, this may take a while...
===> Add debug_info to compiler options (erl_opts) if Dialyzer fails to load Core Erlang.
===> Updating plt...
===> Resolving files...
===> Checking 206 files in _build/default/rebar3_25.1.1_plt...
===> Doing success typing analysis...
===> Resolving files...
===> Analyzing 1 files with _build/default/rebar3_25.1.1_plt...

apps/foo/src/foo.erl
Line 11 Column 2: The contract foo:test_fun(binary()) -> {'get',atom()} cannot be right because the inferred return for test_fun(<<102,111,111>>) on line {16,5} is {'get',<<_:24>>}
Line 15 Column 1: Function test/0 has no local return
===> Warnings written to _build/default/25.1.1.dialyzer_warnings
===> Warnings occurred running dialyzer: 2
Failed

```

**Affected versions**
i found on: rebar 3.17.0 on Erlang/OTP 25 Erts 13.1.1

**Comment by kostis** [comment] 2022-10-23 19:57
Contrary to what most naive programmers may think, Dialyzer was never designed to be -and **is not**- a type checker.

More importantly, it has _never_ promised anybody to flag (all) type violations.  Instead, the only thing it has promised is to that _the discrepancies it reports are definite_.  The keyword in the previous sentence is the last word. (Hence the "Dialyzer is never wrong" slogan).

What the above means, e.g. in this particular case, is the following:
- When the `test_fun/1` function is exported, it is possible that some other module / caller of this function issues a call `foo:test_fun(bar)` and so the spec that the programmer has supplied may possibly be correct.  (Note that Dialyzer has no way of knowing that `foo:test/0` will even be used -- it can e.g. be dead code.  So, it cannot _definitely_ flag the spec as wrong, because for many other uses, it may be correct.  Also, note that in your example, the `test/1` function does not have any spec, so even `test` is OK as far as Dialyzer is concerned.)
- On the other hand, when the `test_fun/1` function is module-local, dialyzer's analysis can _prove_ that now it knows **all** callers of that function, and in that case it can _prove_ that the spec is violated by the call -- and some definite type discrepancy is detected.

Bottomline: No matter how counter-intuitive some naive programmers may find this behavior, this is as it should be.

(This does not mean that this cannot be improved.  In fact, it can.  However, the analysis that this requires is quite subtle.)

**Comment by bjorng** [comment] 2022-10-24 11:25
I am closing this because it is not a bug.

**Closed** 2022-10-24 11:25 UTC
Labels: team:VM, bug
