### ISSUE TITLE
pg may crash when confusing multiple monitors

### ISSUE THREAD

**Issue by uwiger** [erlang/otp#7754] opened 2023-10-15 17:04 UTC
**Describe the bug**
If a process calls on `pg` to both monitor a group and join a group, and then crashes, `pg` may crash too, e.g. assuming that the first `'DOWN'` message received is for the `Local` group membership monitor, rather than for the group monitor operation.

**To Reproduce**
```
uwiger@uwmbp locks % erl -kernel start_pg true
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Eshell V13.2.2  (abort with ^G)
1> whereis(pg).
<0.70.0>
2> pg:monitor(mygroup).
{#Ref<0.3554009589.1341915140.4510>,[]}
3> pg:join(mygroup,[self()]).
ok
4> exit(foo).
=ERROR REPORT==== 15-Oct-2023::18:52:51.674230 ===
** Generic server pg terminating 
** Last message in was {'DOWN',#Ref<0.3554009589.1341915140.4510>,process,
                               <0.86.0>,normal}
** When Server state == {state,pg,
                               #{<0.86.0> =>
                                     {#Ref<0.3554009589.1341915140.4518>,
                                      [mygroup]}},
                               #{},#{},
                               #{#Ref<0.3554009589.1341915140.4510> =>
                                     {<0.86.0>,mygroup}},
                               #{mygroup =>
                                     [{<0.86.0>,
                                       #Ref<0.3554009589.1341915140.4510>}]}}
** Reason for termination ==
** {{case_clause,{{#Ref<0.3554009589.1341915140.4518>,[mygroup]},#{}}},
    [{pg,handle_info,2,[{file,"pg.erl"},{line,413}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,1123}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1200}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
```
**Expected behavior**
`pg` should remember that it can have multiple monitors to the same pid, and allow for this in the pattern matching.
Specifically, when [receiving a 'DOWN' message](https://github.com/erlang/otp/blob/OTP-25.3.2.7/lib/kernel/src/pg.erl#L413-L416), it doesn't do this.

**Affected versions**
The error seems to have been introduced in OTP 25.1 and affecting all subsequent versions.

**Additional context**

**Comment by jhogberg** [comment] 2023-10-16 10:13
Duplicate of #7625

**Closed by jhogberg** 2023-10-16 10:13 UTC
Labels: team:VM, duplicate, bug
