### ISSUE TITLE
The inliner doesn't inline

### ISSUE THREAD

**Issue by michalmuskala** [erlang/otp#6162] opened 2022-07-20 12:30 UTC
**Describe the bug**
In specific code with simple arithmetic operations (where the function call overhead is significant), neither the heuristic-based inliner (with `-compile(inline)`) or even the explicit inliner with `-compile({inline, [...]})` don't inline the functions.
Manually inlining the functions (vs nothing inlined) gives about 30-40% speedup.

**To Reproduce**
```erl
$ cat not_inlined.erl
-module(not_inlined).

-export([hash/2]).

-compile({inline, [h/2, fun_not_inlined/2, mask32/1, mask64/1]}).

hash(Key, Seed) ->
    Key1 = mask32(Key),
    Key2 = mask64(Key) bsr 32,
    Hash0 = mask32(Seed),
    Hash1 = h(Hash0, Key1),
    Hash2 = h(Hash1, Key2),
    Hash1 bxor (Hash2 bsr 16).

fun_not_inlined(X, N) ->
    mask32(X bsl N) bor mask32(X bsr (32 - N)).

h(Hash, K) ->
    mask32(fun_not_inlined(Hash bxor K, 13) * 5 + 3).

mask32(X) ->
    X band 16#ffffFFFF.

mask64(X) ->
    X band 16#ffffFFFFffffFFFF.
$ erlc +to_asm not_inlined.erl
$ grep 'fun_not_inlined' not_inlined.S
    {call,2,{f,4}}. % fun_not_inlined/2
    {call,2,{f,4}}. % fun_not_inlined/2
{function, fun_not_inlined, 2, 4}.
    {func_info,{atom,not_inlined},{atom,fun_not_inlined},2}.
```

**Expected behavior**
The function should be inlined correctly

**Affected versions**
Latest master

**Comment by bjorng** [comment] 2022-07-25 06:39
The explicit inliner is very naive. To avoid infinite loops caused by inlining a self-recursive function forever, it will not do any any recursive inlining. For your particular example, `h/2` will be inlined (twice) into `hash/2`, but then no further attempts to do inlining into `hash/2` will be done.

It would probably not be too difficult to improve the explicit inliner to do a better job (for example by building a call graph and only limit inlining for functions with cycles in the graph), but doing it currently has low priority for the compiler team.

The implicit inliner can be made more aggressive by giving the `{inline_size,Size}` option. However, for some reason, it seems that the implicit inliner for some reason will never inline `mask32/1` however high I set `Size`. Investigating this issue has  low priority for the compiler team.

For your particular example, complete inlining can be achieved by using both inliners in the following way:

```
-compile({inline, [h/2, fun_not_inlined/2, mask32/1, mask64/1]}).
-compile([inline, {inline_size,28}]).
```

**Closed** 2022-08-02 04:33 UTC
Labels: team:VM, bug
