### ISSUE TITLE
beam.smp and ssl.beam are not deterministic between different compilations

### ISSUE THREAD

**Issue by EricLin89** [erlang/otp#5555] opened 2021-12-29 04:00 UTC
We are using erlang/otp 23.3, and are trying to make builds reproducible.

After fixing all the possible variants, such as build directories, timestamps, randoms, etc. 2 files(beam.smp and ssl.beam) from the compilation result are still inconsistent.

For beam.smp, the objdump output of 2 build results shows something like different address offset(not sure about it), which looks like:

<html>
<body>

14 | »       lea····0x3a805a(%rip),%r8········ | 14 | »       lea····0x3a806a(%rip),%r8········
-- | -- | -- | --
15 | »       lea····0x3a7fe3(%rip),%rcx········ | 15 | »       lea····0x3a7ff3(%rip),%rcx········

</body>
</html>
<html>
<body>

90 | »       callq··110858·<erl_start@@Base> | 90 | »       callq··110868·<erl_start@@Base>
-- | -- | -- | --

</body>
</html>

For ssl.beam, the binary diff shows some repeated patterns(no idea what it means):
<html>
<body>

000080f0:·0000·034c·0000·0000·0000·0001·039f·d82c··...L..........., | 000080f0:·0000·034c·0000·0000·0000·0001·059d·9622··...L..........."
-- | --
00008100:·0000·01a7·0000·0001·0000·034a·0000·0001··...........J.... | 00008100:·0000·01a7·0000·0001·0000·034a·0000·0001··...........J....
00008110:·0000·0000·**039f·d82c**·0000·01a6·0000·0001··.......,........ | 00008110:·0000·0000·**059d·9622**·0000·01a6·0000·0001··......."........
00008120:·0000·0348·0000·0002·0000·0000·**039f·d82c**··...H..........., | 00008120:·0000·0348·0000·0002·0000·0000·**059d·9622**··...H..........."
00008130:·0000·01a1·0000·0001·0000·032c·0000·0003··...........,.... | 00008130:·0000·01a1·0000·0001·0000·032c·0000·0003··...........,....
00008140:·0000·0000·**039f·d82c**·0000·01a0·0000·0003··.......,........ | 00008140:·0000·0000·**059d·9622**·0000·01a0·0000·0003··......."........
00008150:·0000·0326·0000·0004·0000·0000·**039f·d82c**··...&..........., | 00008150:·0000·0326·0000·0004·0000·0000·**059d·9622**··...&..........."
00008160:·0000·019f·0000·0001·0000·0324·0000·0005··...........$.... | 00008160:·0000·019f·0000·0001·0000·0324·0000·0005··...........$....
00008170:·0000·0000·039f·d82c·0000·019e·0000·0003··.......,........ | 00008170:·0000·0000·059d·9622·0000·019e·0000·0003··......."........
00008180:·0000·031e·0000·0006·0000·0000·039f·d82c··..............., | 00008180:·0000·031e·0000·0006·0000·0000·059d·9622··..............."

</body>
</html>

Could anyone help to determine where the problem is and how to fix it? Binary files can be provided if necessary.

**Comment by garazdawi** [comment] 2021-12-29 07:39
https://github.com/erlang/otp/pull/5153 this PR released in [OTP-24.1](https://www.erlang.org/patches/otp-24.1#OTP-17581) fixes the ssl.beam issue. 

As described in https://github.com/erlang/otp/issues/4417#issuecomment-809286273, GCC does not produce reproducible builds (or at least we have been unable to do so). If you know of any options that should make it so a PR would be most welcome.

**Comment by garazdawi** [comment] 2022-01-03 11:27
Closing this issue as a duplicate of #4417.

**Closed by garazdawi** 2022-01-03 11:27 UTC
Labels: team:VM, bug
