### ISSUE TITLE
`io:get_line/1` input not added to shell history

### ISSUE THREAD

**Issue by moogle19** [erlang/otp#6896] opened 2023-02-20 07:59 UTC
**Describe the bug**
In versions prior to OTP 26 the input of `io:get_line/1` was added to the history (This is used by Elixir's `iex` for example).
Now it ignores that input.

**To Reproduce**
Open `erl` shell, type:
```erlang
1> io:get_line("> ").
> Foo = "bar".
"Foo = \"bar\".\n"
```
and press up.

**Expected behavior**
I am not sure if the "new" behaviour is the intended behaviour or the old one.

**Affected versions**
OTP 26-rc1

**Comment by frazze-jobb** [comment] 2023-02-20 15:53
Hi, the new behavior is the intended behavior, does this break anything in your workflow or something in iex? @josevalim

**Comment by josevalim** [comment] 2023-02-20 19:38
@frazze-jobb yes, previously we were relying on io:get_line behaviour, so now shell history does not work on Elixir. But I assume it is an easy fix on our side? Do you know what we have to call to read the stdin and have the history recorded?

**Comment by frazze-jobb** [comment] 2023-02-21 10:19
Aha,

Currently, group only records get_until requests (which erlang shell uses):
https://github.com/erlang/otp/blob/36a627b8c3d15fce78566c9efa4af63b9368cfbb/lib/stdlib/src/shell.erl#L268-L277
https://github.com/erlang/otp/blob/36a627b8c3d15fce78566c9efa4af63b9368cfbb/lib/stdlib/src/io.erl#L440-L441
https://github.com/erlang/otp/blob/36a627b8c3d15fce78566c9efa4af63b9368cfbb/lib/kernel/src/group.erl#L275-L276

I don't know if its an easy fix on your side, but I can add a special get_line request that can be used by shells, that also records to shell history, if get_until is not suitable in your case.

What do you think @josevalim

**Comment by josevalim** [comment] 2023-02-21 12:49
Ah, excellent, I will give it a try. Looking forward to multiline editing too!

@moogle19 I am tracking this on Elixir side, feel free to close this!

**Closed** 2023-02-21 12:54 UTC
Labels: team:VM, bug

**Comment by josevalim** [comment] 2023-02-23 15:40
@frazze-jobb I was able to adept accordingly but I had to remove one “feature”. Today we change the prompt once it becomes incomplete:

```
iex> 1+
…> 2
```

this gives a clearer indicator to the user that the expression is incomplete. Python has a similar behavior and Ruby too (they use an asterisk). Perhaps it could be useful for Erlang too. We could allow `{more, Continuation, NewPrompt}` from get_until to get this behavior, but it will depend if it is a deemed a good feature for Erlang.

**Comment by josevalim** [comment] 2023-02-23 18:44
I changed my mind. I think the `...>` really improves the user experience. I will try to submit a PR for the more+prompt stuff for your discussion.

**Comment by frazze-jobb** [comment] 2023-02-24 06:05
Yes, we want to show the opening parenthesis in the prompt or just color the unclosed ones not sure that we will settle for. Go ahead with the PR, Im not sure if we want a configurable incomplete prompt or just a standard one that everyone sticks to. Any thoughts on that? Or maybe register a incomplete prompt function. We can continue the discussion in your PR.

**Comment by josevalim** [comment] 2023-02-24 08:56
@frazze-jobb my thought was that `{more, Continuation, Prompt}` would allow all of the options above. For example, imagine you are using:

    request(Io, {get_until,unicode,Prompt,erl_scan,tokens,[Pos0,Options]}).

I think you can replace it by:

    request(Io, {get_until,unicode,Prompt,?MODULE,tokens,[Pos0,Options]}).

where:

```erlang
tokens(Cont, Chars, Pos, Options) ->
  case erl_scan:tokens(Cont, Chars, Pos, Options) of
    {done, _, _} = Done -> Done;
    {more, Cont} -> {more, Cont, "new prompt"}
  end
```

But if you want to use a function, you could pass that to your `tokens` and invoke it. In Elixir we allow people to choose to how both the regular and incomplete prompt look like. A default implementation of the incomplete prompt could be the regular prompt where all characters are converted to `.` (or all characters but last):

```erlang
1> 1 +
.. 2
```

**Comment by josevalim** [comment] 2023-02-24 13:40
PR submitted here: #6921.
