### ISSUE TITLE
internal error in pass beam_ssa_pre_codegen

### ISSUE THREAD

**Issue by yushli** [erlang/otp#6668] opened 2023-01-16 03:09 UTC
**Describe the bug**

test.erl
```
-module(test).

-export([test/1]).

test(Bin) ->
    try
        <<ThisPacket:4/binary, Rest/binary>> = Bin,
        {ThisPacket, Rest}
    catch
        error:_Error -> ok
    end.
```
with latest erlc from main branch, will cause the following error:
```
erlc test.erl 
Sub pass reserve_regs
Function: test/1
test.erl: internal error in pass beam_ssa_pre_codegen:
exception error: no function clause matching beam_ssa_codegen:classify_heap_need(bs_extract) 
  in function  beam_ssa_pre_codegen:res_place_gc_instrs/2 (beam_ssa_pre_codegen.erl, line 2711)
  in call from beam_ssa_pre_codegen:reserve_xregs/4 (beam_ssa_pre_codegen.erl, line 2683)
  in call from beam_ssa_pre_codegen:reserve_regs/1 (beam_ssa_pre_codegen.erl, line 2559)
  in call from compile:run_sub_passes_1/3 (compile.erl, line 422)
  in call from beam_ssa_pre_codegen:function/2 (beam_ssa_pre_codegen.erl, line 160)
  in call from beam_ssa_pre_codegen:functions/2 (beam_ssa_pre_codegen.erl, line 89)
  in call from beam_ssa_pre_codegen:module/2 (beam_ssa_pre_codegen.erl, line 84)

```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Affected versions**
The OTP versions that are affected by this bug.

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by bjorng** [comment] 2023-01-16 04:37
This is a duplicate of #6660 (which is now fixed).

**Closed by bjorng** 2023-01-16 04:37 UTC
Labels: team:VM, bug
