### ISSUE TITLE
Syntax error when using binary or string as a key in a map based type specification

### ISSUE THREAD

**Issue by abalazsik** [erlang/otp#6202] opened 2022-08-08 16:57 UTC
Compiler returns with a syntax error on this code:
```
-type my_type() :: #{
	<<"description">> := binary(),
        "description2" := binary(),
	_ => _
}.
```

**Expected behavior**
The [documentation](https://www.erlang.org/doc/reference_manual/typespec.html) says nothing about binary keys, but I'm expecting that this should compile, because a key in a map can be binary and list.

**Affected versions**
Can be reproduced on Erlang/OTP 25.

**Comment by garazdawi** [comment] 2022-08-08 18:50
Hello!

As you have discovered, string and binary literals are not allowed at all in the Erlang type-language. That is you cannot write this:

```erlang
-type foo() :: "bar".
```
The correct way to type the above would be:

```erlang
-type foo() :: nonempty_string().
```

The same restriction applies to both the key and value part of a map.

I don't know if it is a good idea to allow string literals in types from the perspective of dialyzer. However, when documenting a function I think it would be a very good idea.

**Comment by abalazsik** [comment] 2022-08-08 19:34
If specifying atoms is allowed, then it would make sense, to allow this too. But I don't know what does it mean in the perspective of the dialyzer

**Comment by josevalim** [comment] 2022-08-09 14:08
The "problem" is that strings are lists. The types you can express with list is `[subtype()]` or alternatively `[subtype(), ...]`. So you can express something like `[$b | $a | $r, ...]`, but that includes any non-empty string with any of those characters.

In order to properly support strings, lists would have to be enhanced to support the given subtypes in a specific order and specific amount and that's potentially very complex.

Atoms are quite different, because they are not general collections, such as lists and binaries. And it makes sense that atoms represent themselves as types.

**Comment by abalazsik** [comment] 2022-08-09 15:36
Okay, maybe specification with atoms was a bad example... All I want to say in general is; if I'm able to write a function that matches a string, or a binary, I should be able to write a specification for it.

**Comment by bjorng** [comment] 2022-08-15 11:20
I am closing this issue because it is not a bug.

**Closed** 2022-08-15 11:21 UTC
Labels: team:VM, enhancement
