### ISSUE TITLE
[erlc] hang on small testcase

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6578] opened 2022-12-19 09:47 UTC
On master (whether cherry-picking https://github.com/erlang/otp/pull/6559 and https://github.com/erlang/otp/pull/6575 or not), running erlc on the following testcase:
```erlang
f(X) ->
    <<
        0
     || ((+(is_alive())) <
            [
                f(f(0))
             || X
            ]) andalso ok
    >>.
```
does not terminate even after 3 minutes (I've not waited longer, so it is possible that erlc is merely extremely slow and not completely stuck here). Usually, even programs several order of magnitude larger are compiled in seconds at the very most. And reducing this testcase even a tiny bit makes erlc compile it near-instantly.

**Comment by bjorng** [comment] 2022-12-19 10:51
The compiler is stuck forever in the type optimization pass, never reaching a fixpoint.

**Comment by jhogberg** [comment] 2022-12-20 09:18
Thanks for your report, I'm closing this as a duplicate of #6568 as they have the same cause.

**Closed by jhogberg** 2022-12-20 09:18 UTC
Labels: team:VM, bug
