### ISSUE TITLE
Bug in public_key:sign3 crypto:sign/5 for ed 25519 keys

### ISSUE THREAD

**Issue by jbevemyr** [erlang/otp#6273] opened 2022-09-02 07:36 UTC
**Describe the bug**
The output of sign() has changed between OTP 24 and OTP 25, and I think the OTP 24 behaviour was the correct one.

**To Reproduce**
Data = <<0,0,0,32,115,115,104,45,101,100,50,53,53,49,57,45,99,
  101,114,116,45,118,48,49,64,111,112,101,110,115,115,104,
  46,99,111,109,0,0,0,32,234,199,33,173,176,181,2,34,231,
  79,223,17,243,68,212,212,66,185,240,105,123,242,29,220,
  29,229,177,76,202,199,78,83,0,0,0,32,88,45,14,135,250,
  254,59,91,42,83,161,145,216,236,160,186,22,45,155,197,
  106,183,171,76,93,118,229,212,56,250,83,77,0,0,0,0,0,0,
  0,1,0,0,0,1,0,0,0,24,117,115,101,114,112,97,115,115,45,
  97,100,109,105,110,64,116,101,108,99,111,46,99,111,109,
  0,0,0,10,0,0,0,6,100,111,99,107,101,114,0,0,0,0,0,0,0,0,
  0,0,0,0,99,23,177,51,0,0,0,0,0,0,0,47,0,0,0,10,112,101,
  114,109,105,116,45,112,116,121,0,0,0,0,0,0,0,21,112,101,
  114,109,105,116,45,88,49,49,45,102,111,114,119,97,114,
  100,105,110,103,0,0,0,0,0,0,0,0,0,0,0,51,0,0,0,11,115,
  115,104,45,101,100,50,53,53,49,57,0,0,0,32,220,102,116,
  172,223,159,217,194,32,192,11,12,9,178,22,59,120,192,
  204,203,208,226,128,116,123,94,220,48,94,211,143,140>>.

Key = {ed_pri,ed25519,
        <<220,102,116,172,223,159,217,194,32,192,11,12,9,178,22,
          59,120,192,204,203,208,226,128,116,123,94,220,48,94,211,
          143,140>>,
        <<88,229,22,161,109,141,215,173,94,59,60,44,4,102,200,
          143,136,153,205,224,163,45,28,189,243,255,149,177,14,
          122,44,88>>}.

In OTP 24 (24.3.1)
public_key:sign(Data, sha256, Key).
<<146,108,68,52,86,179,193,243,132,56,145,68,245,14,248,
  12,206,176,2,61,46,39,152,206,164,170,233,153,210,166,
  58,214,200,251,213,12,108,61,15,44,65,220,149,107,153,
  63,216,66,147,115,30,211,25,75,66,218,20,110,55,153,142,
  4,175,4>>

In OTP 25 (25.0.4)
public_key:sign(Data, sha256, Key).
<<54,248,199,48,47,234,252,177,128,107,59,136,218,156,192,
  113,152,39,122,38,59,94,69,255,202,105,227,12,142,160,
  193,93,211,116,245,114,246,231,23,78,139,180,200,155,
  169,4,119,183,59,142,182,155,4,200,45,208,174,77,224,
  223,252,48,19,0>>

**Expected behavior**
The output produced in OTP 24 appears to be the correct one.

**Affected versions**
OTP 25 and later.

**Additional context**
I think the problem  have been introduce in the signing nif in pkey.c

**Comment by IngelaAndin** [comment] 2022-09-02 10:02
Could this be a duplicate of #6219 ?

**Comment by jbevemyr** [comment] 2022-09-02 11:13
> Could this be a duplicate of #6219 ?

Yes, looks like it. When I replace sha256 with none it produces the same result as OTP 24.

**Comment by IngelaAndin** [comment] 2022-09-02 14:05
Then the solution is merged for 25.1 planned for end of November

**Comment by KennethL** [comment] 2022-09-02 15:25
Correction: OTP 25.1 is planned for September 21st

**Comment by IngelaAndin** [comment] 2022-09-02 18:03
Ah, my bad I meant to write the end of September!

**Closed** 2022-09-05 08:17 UTC
Labels: team:PS, duplicate, bug
