### ISSUE TITLE
Supervisor with simple_one_for_one strategy keeps child in his state and it cannot be removed

### ISSUE THREAD

**Issue by Polexy** [erlang/otp#6870] opened 2023-02-16 08:12 UTC
**Describe the bug**
We found such case after our performance testing, supervisior cannot release memory after load
```
| MFA                                    |count       |hib_count   |hib_memory  |memory      |memory %    |reductions  |reductions %|total_binary|unique_binar|
| ---------------------------------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|
| {supervisor,some_client_sup,1}         |1           |0           |0           |58043584    |73.087      |165234018   |0.151       |2227375     |1285115     |
```
we use **simple_one_for_one** stategy and restart  => **transient** for child, as i see we may remove child only when restart => **temporary**
```
terminate_children(Children, SupName) ->
    Terminate =
        fun(_Id,Child) when ?is_temporary(Child) ->
                %% Temporary children should not be restarted and thus should
                %% be skipped when building the list of terminated children.
                do_terminate(Child, SupName),
                remove;
```
and also cannot delete child from state because **simple_one_for_one** 
```
%% delete_child request is invalid for simple_one_for_one supervisors
handle_call({delete_child, _Id}, _From, State) when ?is_simple(State) ->
    {reply, {error, simple_one_for_one}, State};
```
so after `supervisor:terminate_child` supervisor continued keeps child in state and it cannot be cleared
maybe add ability to delete childs manually for  **simple_one_for_one** strategy if `#child{pid=undefined}`

**To Reproduce**
Create supervisior with **simple_one_for_one**  stategy and child restart type non temporary
Create and terminate several childs
Check memory usage for supervisior

**Expected behavior**
Supervisor doesn't keep child in his state for unnecessary childs

**Affected versions**
Erlang/OTP 25 [erts-13.1.1]

**Comment by IngelaAndin** [comment] 2023-02-23 09:23
Do you have a simple_one_for_one child that should be restarted by the supervisor when it crashes? I think it is kind of the common case that you have temporary children under a simple one for one supervisor that are dynamically added when a new processes of the same type but not related to each other is needed. Not saying this is not a bug, but I know that some combinations of supervisor configurations might not always make sense  and there are probably room for improvement in error handling.

**Comment by IngelaAndin** [comment] 2023-03-08 13:42
@Polexy Is the problem the fact that you do not get the cleaning or that you want an automated restart? You do know that your processes will  need to trap exits  for the OTP-process behaviors (gen_server, gen_statem) to for sure run the terminate  callback unless explicitly killed by its supervisor? Same goes for compliant processes implemented with proc_lib.  

You can dynamically add processes to both type of supervisors although simple_one_for_one is made for the dynamic worker processes of the same type that come and go and can be run in many instances simultaneously. Also they are usually pointless to restart as it would be the same as start a new one. A one_for_one supervisor is not expected to have more than one instance of the same type of process even if the children may be started and stopped dynamically. 

It is expected to not remove the child_specification for a non simple_one_for_one supervisor as it is needed to restart the process unless it was marked as temoprary.  

The delete_child is not relevant for simple_one_for_one supervisors as they do not keep child_specs. I think it is probably uncommon to use this kind of manual adding and deleting and possible calls to restart_child. 

You did use the pid to terminate the simple_one_for_one  children? 

Currently I do not have time to play around with this.  Am I understanding your problem? Could you perhaps create a simple example the I or my coworkers could run to demonstrate the problem?

**Comment by Polexy** [comment] 2023-03-09 11:22
the problem that supervisor continue keeps child in his state even after terminate. 
We can add children dynamically and terminate, but supervisor don't clean it

Code:
```
%% simple_sup.erl
-module(simple_sup).

-behaviour(supervisor).

-export([start_link/0, init/1]).
-export([new_client/0, terminate_client/1]).
-export([test/1, info/0]).

start_link() ->
    supervisor:start_link({local, ?MODULE}, ?MODULE, []).

init([]) ->
    AChild = #{id => 'simple_worker',
        start => {'simple_worker', start_link, []},
        restart => transient,
        shutdown => 2000,
        type => worker,
        modules => ['simple_worker']},

    {ok, {#{strategy => simple_one_for_one,
        intensity => 5,
        period => 30},
        [AChild]}
    }.


new_client() ->
    supervisor:start_child(?MODULE, []).

terminate_client(Pid) ->
    supervisor:terminate_child(?MODULE, Pid).


test(N) ->
    info(),
    Pids = [simple_sup:new_client() || _X <- lists:seq(1, N)],
    info(),
    [simple_sup:terminate_client(Pid) || {ok, Pid} <- Pids],
    info().


info() ->
    Sup = erlang:whereis(simple_sup),
    {memory, Mem} = erlang:process_info(Sup, memory),
    Children = supervisor:count_children(Sup),
    io:format("Children: ~p, memory: ~p~n", [Children, Mem]).

```
```
%% simple_worker.erl
-module(simple_worker).

-behaviour(gen_server).

-export([start_link/0]).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2,
    code_change/3]).

-define(SERVER, ?MODULE).

-record(simple_worker_state, {}).

%%%===================================================================
%%% Spawning and gen_server implementation
%%%===================================================================

start_link() ->
    gen_server:start_link({global, make_ref()}, ?MODULE, [], []).

init([]) ->
    {ok, #simple_worker_state{}}.

handle_call(_Request, _From, State = #simple_worker_state{}) ->
    {reply, ok, State}.

handle_cast(_Request, State = #simple_worker_state{}) ->
    {noreply, State}.

handle_info(_Info, State = #simple_worker_state{}) ->
    {noreply, State}.

terminate(_Reason, _State = #simple_worker_state{}) ->
    ok.

code_change(_OldVsn, State = #simple_worker_state{}, _Extra) ->
    {ok, State}.
```

And results:
```
1> simple_sup:start_link().
{ok,<0.147.0>}
2> simple_sup:test(10).
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 2768
Children: [{specs,1},{active,10},{supervisors,0},{workers,10}], memory: 7320
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 11872
ok
3> simple_sup:test(100).
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 11872
Children: [{specs,1},{active,100},{supervisors,0},{workers,100}], memory: 15808
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 42952
ok
4> simple_sup:test(1000).
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 42952
Children: [{specs,1},{active,1000},{supervisors,0},{workers,1000}], memory: 128560
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 284632
ok
5> 
5> simple_sup:test(10000).
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 284632
Children: [{specs,1},{active,10000},{supervisors,0},{workers,10000}], memory: 1515040
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 691168
ok
6> 
6> simple_sup:info().     
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 691168

7> simple_sup:test(10000).
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 691168
Children: [{specs,1},{active,10000},{supervisors,0},{workers,10000}], memory: 1515040
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 1116480
ok


```

**Comment by IngelaAndin** [comment] 2023-04-07 06:55
@Polexy  Thank you for the input we will make some time after RC3 (Release Candidate 3 of OTP-26) and the Easter holidays to look into this further.

**Comment by IngelaAndin** [comment] 2023-05-03 13:39
Due to many other issues taking priority this has been postponed to after OTP-26.0

**Comment by juhlig** [comment] 2023-09-06 20:09
Out of curiosity, I investigated a little in this matter. Here are my findings.

<hr />

The supervisor keeps nothing unexpected in it's state, as you can see with `sys:get_state` after the `simple_sup:test` calls:
```erlang
1> {ok, P}=simple_sup:start_link().
{ok,<0.84.0>}
2> simple_sup:test(10).
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 2768
Children: [{specs,1},{active,10},{supervisors,0},{workers,10}], memory: 7320
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 11872
ok
3> sys:get_state(P).      
{state,{local,simple_sup},
       simple_one_for_one,
       {[simple_worker],
        #{simple_worker =>
              {child,undefined,simple_worker,
                     {simple_worker,start_link,[]},
                     transient,false,2000,worker,
                     [simple_worker]}}},
       {maps,#{}},
       5,30,[],0,never,simple_sup,[]}
```
There is nothing unexpected in the process dictionary, either:
```erlang
4> erlang:process_info(P, dictionary).
{dictionary,[{'$initial_call',{supervisor,simple_sup,1}},
             {'$ancestors',[<0.82.0>]}]}
```

So yes, the supervisor process seems to be "gaining weight" memory-wise, but not because of anything in its state or the process dictionary. This should probably be investigated, but my expertise ends here --> back to @IngelaAndin (sorry :sweat_smile:)

<hr />

The behavior is not related to the `transient` restart strategy, I get the exact same behavior if I change the restart strategy to `temporary`.

<hr />

Btw, @Polexy...
> ... maybe add ability to delete childs manually for simple_one_for_one strategy...

This is not possible, and maybe you misunderstand what `delete_child` does in general, and in `simple_one_for_one` supervisors specifically? `delete_child` does not remove a child but the child _spec_, ie the instructions how to set up a child.

Now, in the other supervisor types, the child spec is stored for each child separately, as they may be (and likely are) different for each. But a `simple_one_for_one` supervisor is different, it stores only 1 child spec (and for that reason, requires exactly 1 child spec in the supervisor setup), which is shared for _all_ its children: no matter how many children you have, there is only 1 child spec stored in the supervisor. And for that reason, you cannot use `delete_child` on a `simple_one_for_one` supervisor.

**Comment by IngelaAndin** [comment] 2023-09-07 08:36
@Polexy Sorry for the delay, I finally found some time to look into this. And as @juhlig correctly points out simple_one_for_one supervisors are special in the way that there is one child specification to start all its children that runs the same code but the processes are independent of each other.  So there is no child specification that should be deleted.  I think your observations comes down to garbage-collecting.  When forcing garbage collecting  I get the following result:

```
1> simple_sup:start_link().
{ok,<0.92.0>}
2> simple_sup:test(10).
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 2736
Children: [{specs,1},{active,1},{supervisors,0},{workers,1}], memory: 2776
Children: [{specs,1},{active,0},{supervisors,0},{workers,0}], memory: 2736
ok
```

This is how I did that:

```

%% simple_sup.erl
-module(simple_sup).

-behaviour(supervisor).

-export([start_link/0, init/1]).
-export([new_client/0, terminate_client/1]).
-export([test/1, info/1]).

start_link() ->
    supervisor:start_link({local, ?MODULE}, ?MODULE, []).

init([]) ->
    AChild = #{id => 'simple_worker',
        start => {'simple_worker', start_link, []},
        restart => transient,
        shutdown => 2000,
        type => worker,
        modules => ['simple_worker']},

    {ok, {#{strategy => simple_one_for_one,
        intensity => 5,
        period => 30},
        [AChild]}
    }.


new_client() ->
    supervisor:start_child(?MODULE, []).

terminate_client(Pid) ->
    supervisor:terminate_child(?MODULE, Pid).


test(N) ->
    Sup = erlang:whereis(simple_sup),
    info(Sup),
    Pids = [simple_sup:new_client() || _X <- lists:seq(1, N)],
    erlang:garbage_collect(Sup),
    info(Sup),
    [simple_sup:terminate_client(Pid) || {ok, Pid} <- Pids],
    erlang:garbage_collect(Sup),
    info(Sup).


info(Sup) ->
    {memory, Mem} = erlang:process_info(Sup, memory),
    Children = supervisor:count_children(Sup),
    io:format("Children: ~p, memory: ~p~n", [Children, Mem]).

  
```

**Closed by IngelaAndin** 2023-09-07 08:36 UTC
Labels: team:PS, not a bug, bug

**Comment by max-au** [comment] 2023-09-15 03:31
> So yes, the supervisor process seems to be "gaining weight" memory-wise, but not because of anything in its state or the process dictionary. 

Could it be the "good old garbage" issue #5608 ?

**Comment by IngelaAndin** [comment] 2023-09-15 06:38
Well, I guess you could say that. The solution we  implemented for that issue  (i.e hibernation) helps with memory consumption of static supervisor that just start a bunch of children and then are expected to do nothing unless something goes wrong or something is shutdown. But simple_one_for_one supervisors have a dynamic nature and are expected to get more work with children coming and going all the time so they are not suited for automatic hibernation.
