### ISSUE TITLE
Growth beyond max of `client_ssl_otp_session_cache` ETS table

### ISSUE THREAD

**Issue by gaberduty** [erlang/otp#6549] opened 2022-12-13 20:39 UTC
**Describe the bug**
We updated from 24.2.2 to 24.3.4 and found that a memory leak related to `ssl_manager` caused the application to crash after several hours.

Specifically, we noticed that the `client_ssl_otp_session_cache` table was growing seemingly without bound. On 24.2.2 `:ets.i()` shows `client_ssl_otp_session_cache` hanging out around 850 rows. On 24.3.4, I sampled `:ets.i()` periodically and saw it having 2,000 rows shortly after deploy, 6,000 rows about 10 minutes later, then 15,000 rows 20 minutes after that, then 23,000 rows 20 minutes later. I used `:sys.get_state(Process.whereis(:ssl_manager))` to confirm that the timeout was the default `86400` and that `session_cache_client_max` was the default `1000`.

**To Reproduce**
We couldn't reproduce this in our staging or load test environment, but it consistently happens on our production environment. The application sends webhooks that our users configure, and so has a huge variety of different outbound server hosts, and we have 1,000 worker processes doing these sends, so it could have to do with a concurrency race condition or something like that.

All of the requests are via `:hackney.request(...)` which sets `{reuse_sessions, true}`.

**Expected behavior**
We expect the size of the `client_ssl_otp_session_cache` to remain under the configured maximum, and to generally behave the same as on the previous OTP minor version.

**Affected versions**
24.2.2 did not exhibit this behavior. We saw it when we upgraded to 24.3.4. We also tried 24.3.4.6 which still had the behavior.

**Additional context**
The app is an Elixir application, on Elixir 1.13 and is deployed to AWS on Ubuntu 20.04.

I'm not too familiar with Erlang or the nitty gritty details of OTP or the `ssl` app, so I'm not sure what else I could provide upfront here, but if I could provide some information that would be helpful let me know. I could deploy one of these versions again and SSH in and poke around to answer questions that might help debug this.

**Comment by IngelaAndin** [comment] 2022-12-14 18:44
This sounds strange indeed. Would it be possible for you to try OTP-25.1 There is another resource bug fixed in this version that could possibly manifest this strange symptom!

**Comment by gaberduty** [comment] 2022-12-14 20:02
Thanks for your quick response! Yes, I think we can try that. Since we'd like to keep potentially breaking branches from being deployed to production all that often... is there any sort of debugging information you think might be helpful that I can collect while it's live? I'll check on the number of entries in `client_ssl_otp_session_cache` via `:ets.i()`, but I'm not sure if anything else might be useful.

**Comment by IngelaAndin** [comment] 2022-12-15 11:20
Well, it could be interesting to know how many children do tls_connection_sup have and does the number correspond to the expected number of open TLS connections.  Does the ssl_manager process owner of the  client_ssl_otp_session_cache have a long queue of messages to handle? In that case what type of messages is filling its inbox?

**Comment by gaberduty** [comment] 2022-12-16 17:33
I just completed an experimental deploy of OTP-25.1.2 and had to rollback because the same issue (`client_ssl_otp_session_cache` was at about 2,500 when I rolled back).

I checked the things you mentioned:

```
> :tls_connection_sup |> Process.whereis() |> Supervisor.count_children()
results: %{active: 1024, specs: 1, supervisors: 1024, workers: 0}

> :ssl_manager |> Process.whereis() |> Process.info(:message_queue_len)
results: {:message_queue_len, 0}

> :ssl_manager |> Process.whereis() |> Process.info(:messages)
results: {:messages, []}
```

and they seem as expected to me. As I mentioned in the initial description, we have 1,000 worker processes sending the webhooks, so the number of `:tls_connection_sup` children seems reasonable to me.

I was poking around in [the code](https://github.com/erlang/otp/blob/cca53fce1e70eb4d509848f71dc5b1d8c5208cfb/lib/ssl/src/ssl_manager.erl#LL510C11-L510C11):

```erlang
        case CacheCb:size(Cache) of
            Max ->
                InternalId = {TimeStamp, erlang:unique_integer([monotonic])},
                Session = Session0#session{internal_id = InternalId},
                {_, OldKey, Order1} = gb_trees:take_smallest(Order0),
                Order = gb_trees:insert(InternalId, Key, Order1),
                CacheCb:delete(Cache, OldKey),
                CacheCb:update(Cache, Key, Session),
```

I don't totally understand all the invariants, but it does seem to me that if `OldKey` isn't in the ETS table for some reason, then the table will grow without bound from then on. Could something have changed in keeping the `Order` tree in sync with the ETS table?

My other thought is that maybe the unbounded ETS table growth is a symptom of some other change, not the primary cause. One thing I noticed is that the `client_ssl_otp_session_cache` table grows *much* more quickly on these later versions. On OTP-24.2 and below, it can take days to get to the table limit of 1,000 entries. On OTP-24.3 and above, we get there (and then beyond) in minutes. And when I page through it with `:ets.i(...)`, I see OTP-24.3+ includes many, many duplicates of `{host, port}` entries (with different session IDs of course), while on `OTP-24.2` there's relatively few duplicates. I almost wonder if *every* new session is unique now.

Did something change about how session IDs are generated or reused? If something changed there, then perhaps with a *lot* more inserts into the `client_ssl_otp_session_cache` table, a race condition to jump over the `Max` size could be more likely to occur.

**Comment by IngelaAndin** [comment] 2022-12-19 08:23
There should be only one process updating the ets table, and if it reaches the max limit of entries it will disregard the oldest entry and make a new entry for the latest insert. (The gb-tree is used to keep track of the entries' relative age as the ets table is just an unordered heap of things. 

Nothing fundamental with generating session ids has changed. I do not have an explanation at the moment, I will keep digging!

**Comment by IngelaAndin** [comment] 2022-12-19 15:59
It is unexpected that there should be many entries for the same server, there should only be one session for each server connection with equivalent options unless you explicitly save a special session using `{reuse_sessions, save} `option in the client. 

I currently do not see how "oldkey" should not be in the ets table but if you could show that is what happens it should of course be possible to figure out why!

**Comment by IngelaAndin** [comment] 2022-12-20 14:14
Well after playing around with the code I think it is probably not a problem that you get more entries in the table for the same server. It is of course a problem however if the max can be exceeded. The reason why you get more entries is that the parallelism has improved. And session resumption will not happen until one handshake has succeeded successfully and managed to register the session. So a client that wants to get the most out of session reuse should first make a single handshake using the {reuse_seesion, save} option to make the session registration synchronous, and when it returns spawn a lot of client connections. Spawning a lot of client connections from the start will probably end up with a hand full of new connections succeeding before the first session is properly registered and can be used for resumption and recognized as equivalent. Will keep digging!

**Comment by IngelaAndin** [comment] 2022-12-20 17:25
@gaberduty  I still have not been able to reproduce it so I made a new branch that I hope you can try. With some logging to prove or disprove your theory. I also added a reset of the session database if the max is exceeded, so it could hopefully also work as a workaround to your problem. 

 https://github.com/IngelaAndin/otp/ingela/ssl/log-session-table-handling

**Comment by gaberduty** [comment] 2022-12-20 18:13
Thank you! My company will be going into a code freeze period over the holidays so I won't be able to deploy that until the new year, but I will let you know when I do. Also, when I try that link I get a 404.

**Comment by IngelaAndin** [comment] 2022-12-20 18:45
Updated the link so it is my branch ingela/ssl/log-session-table-handling in my GitHub repo  git@github.com:IngelaAndin/otp.git

**Comment by IngelaAndin** [comment] 2023-01-10 10:11
@gaberduty  Have you had a chance to test yet?

**Comment by mikpe** [comment] 2023-01-16 15:28
We're seeing this issue right now with OTP-23.3.4.18. Currently we have an `ssl_manager` process where the `session_cache_client` ETS  has 654 entries but the `client_session_order` gb_tree has a whopping 687706 entries. My understanding of the code is that these two storages should contain the same entries.

A co-worker says this has happened before (years ago), but it's not a common occurrence (at least not to the point where we notice it).

**Comment by gaberduty** [comment] 2023-01-18 13:55
@IngelaAndin - I haven't been able to test it yet. The way our deploy infrastructure works, it relies on `asdf` and `kerl` to install Erlang, and I haven't been able to figure out how to install Erlang from a custom GitHub branch. And, unfortunately, this problem has been de-prioritized internally since we're okay using `24.2.2` for now, so I probably won't have time to work on it for a while. Sorry!

**Comment by IngelaAndin** [comment] 2023-01-25 11:19
@gaberduty Ok, please let me know when you have time. We will have it as a general thing to try to investigate but I am afraid it will not get top priority until we are able to reproduce the issue.

**Comment by IngelaAndin** [comment] 2023-05-17 10:59
@gaberduty  any updates on this?

**Closed** 2023-05-30 15:00 UTC
Labels: team:PS, cannot reproduce, bug
