### ISSUE TITLE
export opaque wrapper for re:mp/0

### ISSUE THREAD

**Issue by mheiber** [erlang/otp#4969] opened 2021-06-15 11:27 UTC
**Is your feature request related to a problem? Please describe.**

We have code that abstracts over `re` functions, which have `re:mp/0` as a parameter type.

Our workaround of having our own type that repeats the definition of `ets:type/1` is awkward and not forwards-compatible.

**Describe the solution you'd like**

Export re:mp/0

**Describe alternatives you've considered**

workaround described above

**Additional context**

In general, when a type is mentioned in exported functions of a module, it makes sense to me to either:
- expose the type
- if implementation-hiding is necessary, create an opaque wrapper. Expose the opaque wrapper and use the opaque wrapper in specs for exported functions

If this rule sounds reasonable, it could perhaps be enforced via a linter.

related issues:
- https://github.com/erlang/otp/issues/4968
- https://github.com/erlang/otp/issues/4970

**Comment by garazdawi** [comment] 2022-01-25 14:25
Duplicate of #5280

**Closed** 2022-01-25 16:52 UTC
Labels: team:VM, enhancement, types
