### ISSUE TITLE
[erlc] internal error in pass beam_ssa_opt, sub pass ssa_opt_type_continue

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6664] opened 2023-01-13 10:34 UTC
**Describe the bug**
```erlang
f(X, #{0 := X, 0 := Y}, Y = [_ | _]) ->
    try
        Y = ok
    catch
        _ ->
            [_ | []] = Y = X
    end.
```
crashes erlc with
```
Function: f/3
Sub pass ssa_opt_type_continue
Function: f/3
minimized/ssa_opt.erl: internal error in pass beam_ssa_opt:
exception error: no match of right hand side value any
  in function  beam_ssa_type:type/5 (beam_ssa_type.erl, line 2156)
  in call from beam_ssa_type:update_types/3 (beam_ssa_type.erl, line 2046)
  in call from beam_ssa_type:simplify/5 (beam_ssa_type.erl, line 1051)
  in call from beam_ssa_type:opt_is/8 (beam_ssa_type.erl, line 589)
  in call from beam_ssa_type:opt_bs/8 (beam_ssa_type.erl, line 530)
  in call from beam_ssa_type:do_opt_function/6 (beam_ssa_type.erl, line 508)
  in call from beam_ssa_type:opt_function/6 (beam_ssa_type.erl, line 481)
  in call from beam_ssa_opt:ssa_opt_type_continue/1 (beam_ssa_opt.erl, line 434)
```

**Affected versions**
- master
- master + #6663 + #6651 + #6659

**Comment by bjorng** [comment] 2023-01-13 11:49
This seems to be a duplicate of #6599.

**Closed by bjorng** 2023-01-13 11:49 UTC
Labels: team:VM, bug
