### ISSUE TITLE
Links on types across module documentation are broken

### ISSUE THREAD

**Issue by DianaOlympos** [erlang/otp#4849] opened 2021-05-19 08:19 UTC
**Describe the bug**
It seems that the links for types that are in another module do not get translated properly in edocs

**To Reproduce**
Got to https://erlang.org/doc/man/gen_udp.html#open-2, check that the link to the inet typespec are broken, on the form https://erlang.org/doc/apps/http///www.erlang.org/edoc/doc/kernel/doc/inet.html.html#type-port_number

**Expected behavior**
The doc should probably be https://erlang.org/doc/man/inet.html.html#type-port_number

**Affected versions**
OTP 24 it seems, did not went back in time to check but iirc it was working before

**Additional context**
Not checked yet if i could reproduce locally or if i could track where it come from, i may do it later tomorrow if I get time.

**Comment by garazdawi** [comment] 2021-05-20 07:28
Thanks for reporting this! This seems to be caused by the new edoc updates not being properly handled by erl_docgen. I'm checking what we might do about it and then I guess we will have to republish the docs.

**Comment by garazdawi** [comment] 2021-05-25 08:26
Fix merged, will keep this issue open until after we update the docs on erlang.org to be correct.

**Comment by garazdawi** [comment] 2021-06-02 07:06
new docs uploaded to http://erlang.org/doc, so everything should work now.

**Closed by garazdawi** 2021-06-02 07:06 UTC
Labels: bug, team:VM
