### ISSUE TITLE
dialyzer: inconsistent/incorrect handling of opaque types.

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#5923] opened 2022-04-21 21:50 UTC
**Describe the bug**

Dialyzer reports "Invalid type specification" for "obviously correct" code.  

The code:

Module `user`:

```erlang
-module(user).

-export([from_binary/1]).
-export_type([id/0, user/0]).

-record(user, {id :: id()}).

-opaque user() :: #user{}.
-opaque id() :: binary().

-spec from_binary(binary()) -> user().
from_binary(B) ->
  #user{id = B}.
```

Module `my_app`:

```erlang
-module(my_app).

-export([user_from_binary/1]).

-spec user_from_binary(binary()) -> user:user().
user_from_binary(B) ->
  user:from_binary(B).
```

Dialyzing:

```
% dialyzer user.erl my_app.erl 
my_app.erl:5:2: Invalid type specification for function my_app:user_from_binary/1. The success typing is 
          (user:id()) -> user:user()
...
done (warnings were emitted)
```

-----

**Expected behavior**

I expect no errors/warnings here since the code doesn't go against any principles of opaque types as described in https://www.erlang.org/doc/reference_manual/typespec.html#type-declarations-of-user-defined-types

> Types declared as opaque represent sets of terms whose structure is not supposed to be visible from outside of their defining module. That is, only the module defining them is allowed to depend on their term structure.

(Since `user:id()` is an (opaque) alias to `binary()`, - the message is misleading in the first place. If there are any "opacity violations" - they should be reported as opacity violations. But there are no opacity violations in this code from my point of view).

-----

**Affected versions**
This bug can be reproduced with 25.0-rc3 and with 24.3.3

-----

**Additional context**

It seems that this behaviour may be record-specific. Using a tagged tuple instead of the record is OK:

Module `user1`:

```erlang
-module(user1).

-export([from_binary/1]).
-export_type([id/0, user1/0]).

-type user1() :: {user1, Id :: id()}.
-opaque id() :: binary().

-spec from_binary(binary()) -> user1().
from_binary(B) ->
  {user1, B}.
```

Module `my_app1`:

```erlang
-module(my_app1).

-export([user1_from_binary/1]).

-spec user1_from_binary(binary()) -> user1:user1().
user1_from_binary(B) ->
  user1:from_binary(B).
```

Dialyzing - no error:

```
% dialyzer user1.erl my_app1.erl
...
done (passed successfully)
```

**Comment by jhogberg** [comment] 2022-04-22 15:28
Thanks for your report! This is tricky but not a bug.

> Since `user:id()` is an (opaque) alias to `binary()`

No, it's saying that `user:id/0` is a subtype of `binary()`: all `id`s are binaries but not all binaries are `id`s. The distinction is very important in this case.

When you say:

```erlang
-spec from_binary(binary()) -> user().
```

You're not overriding what `dialyzer` has figured out on its own, you're placing an additional constraint on the function saying that it can only succeed when the input is a subtype of `binary()`. If `dialyzer` has figured out a more precise type then it will use that.

It's a bit easier to illustrate this with plain integers:

```erlang
%% user.erl
-spec foobar(integer()) -> ok.
foobar(0) -> ok.

%% my_app.erl
foobar() ->
   %% my_app.erl:9:1: Function foobar/0 has no local return
   %% my_app.erl:9:25: The call user:foobar
   %%          (1) will never return since it differs in the 1st argument from the success typing arguments: 
   %%          (0)
   user:foobar(1).
```

Going back to your example:

```erlang
-spec from_binary(binary()) -> user().
from_binary(B) ->
  #user{id = B}.
```

Since we cannot assign any random binary to `#user.id`, but specifically only a `user:id/0`, the function can only succeed when given a `user:id/0`, making the actual signature:

```erlang
-spec from_binary(id()) -> user().
```

Because this is in the module that defined `user:id/0`, we know that `binary()` is a supertype of `user:id/0`, and as such the specification for `user:from_binary/1` is technically valid (albeit underspecified).

From the perspective of `my_app` however, we're passing a binary to a function that expects the unknown opaque type `user:id/0`, and we indirectly call out the opacity violation by saying the spec is invalid. The warning is correct but could've been better.

As an aside, if our knowledge of it being a binary came from something other than the bad spec, then we would have gotten a more explicit warning:

```erlang
%% my_app.erl
user_from_binary(B) when is_binary(B) ->
    %% my_app.erl:5:1: Function user_from_binary/1 has no local return
    %% my_app.erl:6:22: The call user:from_binary
    %%          (B :: binary()) does not have an opaque term of type 
    %%           user:id() as 1st argument
    user:from_binary(B).
```

So far so good, but why does it work when `user:from_binary/1` returns a tuple instead of a record?

```erlang
-spec record(binary()) -> user().
record(B) ->
  #user{id = B}.

-spec tuple(binary()) -> user().
tuple(B) ->
  {user, B}.
```

In `record/1`, `B` already has to be a `user:id/0` for the function to succeed, whereas `tuple/1` has no such requirements and will succeed when given any binary.

I suggest changing your code to the following instead:

```erlang
-spec user_id_from_binary(binary()) -> id().
user_id_from_binary(B) ->
    %% Do whatever verification you want on `B`.
    B.

-spec from_binary(binary()) -> user().
from_binary(B) ->
  #user{id = user_id_from_binary(B)}.
```

**Comment by ilya-klyuchnikov** [comment] 2022-04-22 22:44
> Since we cannot assign any random binary to #user.id, but specifically only a user:id/0, the function can only **succeed**when given a user:id/0, making the actual signature.

Can you clarify what "to succeed" means here? 

Clearly, it doesn't mean "to succeed AT RUNTIME", - since there is no problem at runtime (for this particular code) to assign any value to #user.id. Correct?

Eg. this code is OK at runtime:

```
MyRec = #user{id = "String"}.
```

----


TBH, I find your explanation not convincing, - since in the example with `foobar` you appeal to runtime behaviour and runtime crashes and use the term "to succeed" as "to not crash at runtime" (using reasoning like "otherwise" it would crash at runtime).

But then coming back to the original Q - there are no problem with runtime at all - only with abstractions/types provided by a user.

**Comment by jhogberg** [comment] 2022-04-22 23:15
> Can you clarify what "to succeed" means here?

Satisfy all constraints.

> TBH, I find your explanation not convincing, - since in the example with foobar you appeal to runtime behaviour and runtime crashes and use the term "to succeed" as "to not crash at runtime" (using reasoning like "otherwise" it would crash at runtime).

`dialyzer` adds constraints according to how things behave at runtime, in the case of my example adding `-spec foobar(0) -> ok.` "under the hood."

They are just as valid as the ones you provide through `-spec`, `-type`, etc.

> Eg. this code is OK at runtime:
>
> `MyRec = #user{id = "String"}.`

Yes, but it breaks the constraint that `user.id/0` must be a `#user.id` (which you gave), therefore it cannot succeed.

> But then coming back to the original Q - there are no problem with runtime at all - only with abstractions/types provided by a user.

Well, yes? You gave it an impossible constraint, that is what `dialyzer` means when it says "invalid specification."

**Comment by ilya-klyuchnikov** [comment] 2022-04-23 11:12
> Satisfy all constraints.

> These constraints are just as valid as the ones you provide through -spec, -type, etc.

>  you're placing an additional constraint on the function saying that it can only succeed when the input is a subtype of binary()
 
 OK, thanks.
 
Taking this interpretation, in light of using tagged tuples instead of records then:

Module user1:

```erlang
-module(user1).

-export([from_binary/1]).
-export_type([id/0, user1/0]).

-type user1() :: {user1, Id :: id()}.
-opaque id() :: binary().

-spec from_binary(binary()) -> user1().
from_binary(B) ->
  {user1, B}.
```

Note that in type `user1()` - the second element should be `id()`.

The spec `user1:from_binary/1` states the constraint that the *function succeeds only* if the result is `user1()`, - meaning that B cannot be an arbitrary binary, but should be `id()`. 

---

But dialyzer reports nothing for this case.

Is it correct to say then that in this case dialyzer misses the error (according to your logic)?

thanks

**Comment by jhogberg** [comment] 2022-04-23 12:26
> The spec user1:from_binary/1 states the constraint that the function succeeds only if the result is user1(), - meaning that B cannot be an arbitrary binary, but should be id().

`-spec from_binary(binary()) -> user1().` adds an additional subtype constraint saying that the return value is `user1/0`, but adds no constraints on the values that _form_ the return value (`B` et al).

It might make more sense when you read the constraints separately:

```erlang
ReturnValue :: {user1, B}, %% From returning
ReturnValue :: user1().    %% From the spec
```

(Note that "subtype of," `::`, is unidirectional)

> Is it correct to say then that in this case dialyzer misses the error (according to your logic)?

In a sense, yes. It would make a lot of sense to also constrain the values that form the return value, I think it's strange that we don't get warnings for code like the following:

```erlang
-export([foo/1, bar/1]).

foo() -> bar(<<>>).

-spec bar(binary()) -> integer().
bar(I) -> I.
```

But alas, we don't.

**Comment by michallepicki** [comment] 2022-04-24 08:35
Would it be a fair assessment to say that Dialyzer `-record` declarations are similar to arguments types in function specs (as opposed to `-type` declarations which are more similar to function return types)? And the difference between literal tuple construction and "literal" record is that record construction arguments are being additionally checked to be of declared types, like in function application.

**Comment by jhogberg** [comment] 2022-04-24 10:18
Sort of, `-record` and `-type` are pretty much identical aside from the former constraining types when the record syntax is used.  You're not going to get slapped if you use `setelement/3` or literal tuple construction instead of going through the record syntax, but just like with `-type` you will get errors if you force an illegal type into a field and then use it somewhere.

```erlang
-record(bar, { tag :: integer() }).

-spec foo(_) -> #bar{}.
foo(_) ->
    Foo = {bar, illegal},
    %% t.erl:9:5: Matching of pattern 
    %%          {'bar', _} tagged with a record name violates the declared type of 
    %%          #bar{tag :: 'illegal'}
    Foo#bar{tag=0}.

-spec quux(_) -> #bar{}.
quux(_) ->
    %% t.erl:11:2: Invalid type specification for function t:quux/1. The success typing is 
    %%          (_) -> #bar{tag :: 'illegal'}
    {bar, illegal}.
```

Needless to say, it's a bad idea to mix the two.

**Comment by ilya-klyuchnikov** [comment] 2022-04-25 08:49
Ok, - I took your point.

----

I feel that the way how the signal is reported is very confusing:

The code:

Module user:
```erlang
-module(user).

-export([from_binary/1]).
-export_type([id/0, user/0]).

-record(user, {id :: id()}).

-opaque user() :: #user{}.
-opaque id() :: binary().

-spec from_binary(binary()) -> user().
from_binary(B) ->
  #user{id = B}.
```

Module my_app:

```erlang
-module(my_app).

-export([user_from_binary/1]).

-spec user_from_binary(binary()) -> user:user().
user_from_binary(B) ->
  user:from_binary(B).
```

Dialyzing:

```
% dialyzer user.erl my_app.erl 
my_app.erl:5:2: Invalid type specification for function my_app:user_from_binary/1. The success typing is 
          (user:id()) -> user:user()
...
done (warnings were emitted)
```

With this reasoning I would expect that it first of all would be reported for `user:from_binary/1` (and optionally for `my_app:user_from_binary/1`).

When dialyzing only `user` module, no errors are reported. Why?

**Comment by jhogberg** [comment] 2022-04-25 10:30
> When dialyzing only user module, no errors are reported. Why?

Because `user:id/0` is known to the `user` module it can see that it's a subtype of `binary/0`. `B :: binary(), B :: user:id()` is trivially satisfied.

In `my_app`, `user:id/0` is unknown and no longer appears as a subtype to `binary/0` but as an opaque type that can't be reconciled with anything. `B :: binary(), B :: user:id()` cannot be satisfied, making the specification invalid.

**Comment by ilya-klyuchnikov** [comment] 2022-04-25 11:03
> B :: binary(), B :: user:id() is trivially satisfied
> No, it's saying that user:id/0 is a subtype of binary(): all ids are binaries but not all binaries are ids. The distinction is very important in this case.

I think that there is a contradiction now))

Since not all binaries are ids - just as you said previously.

**Comment by jhogberg** [comment] 2022-04-25 11:10
> I think that there is a contradiction now))
> 
> Since not all binaries are ids - just as you said previously.

 `B :: binary()` says that the value of `B` can be found in the set of all binaries, `B :: user:id()` says that the value of `B` can be found in the set of all `user:id/0`s.

Combining the two, `B :: binary(), B :: user:id()`, says that the value of `B` can be found in the intersection of the set of all binaries and the set of all `user:id/0`s. The intersection is not empty so therefore there is no contradiction.

**Comment by michallepicki** [comment] 2022-04-25 11:50
> When dialyzing only user module, no errors are reported. Why?

I think that's because specdiffs (overspecs and underspecs) are not reported by Dialyzer by default

**Comment by jhogberg** [comment] 2022-04-25 11:54
> I think that's because specdiffs (overspecs and underspecs) are not reported by Dialyzer by default

Yeah, if you turn on `-Wunderspecs` it'll tell you that `user:from_binary/1` is underspecified as `binary/0` is a strict supertype of `user:id/0`. It's off by default because strictly speaking it's not an error.

**Comment by jhogberg** [comment] 2022-04-25 13:57
> Even if this is correct according to the current rules, I don't think it's particularly useful, or perhaps even actively harmful.

At the very least it's confusing. :-(

> The main point of a "constructor" function like user:from_binary/1 is producing an opaque value from something not opaque. But now dialyzer is requiring that in order to call this "constructor" function, I need to already have the opaque value probably by calling the constructor function. But this is exactly the function I'm trying to call.

It's not `dialyzer` requiring it, but the specification for `#user{}` that says `#user.id` must be a `user:id/0`. Things are fine you add another "constructor" for that:

```erlang
-spec user_id_from_binary(binary()) -> id().
user_id_from_binary(B) ->
    %% Do whatever verification you want on `B`.
    B.

-spec from_binary(binary()) -> user().
from_binary(B) ->
  #user{id = user_id_from_binary(B)}.
```

**Comment by elbrujohalcon** [comment] 2022-04-25 13:58
HA! I had the same idea as @jhogberg!
I was writing this when his comment came in. I'll leave my comment here anyway, just in case…

Another data point: If you add an internal function to turn a `binary()` into a `user:id()`, then Dialyzer remains quiet…

```erlang
-module(user).

-export([from_binary/1]).
-export_type([id/0, user/0]).

-record(user, {id :: id()}).

-opaque user() :: #user{}.
-opaque id() :: binary().

-spec from_binary(binary()) -> user().
from_binary(B) ->
  #user{id = id_from_binary(B)}.

-spec id_from_binary(binary()) -> id().
id_from_binary(B) -> B.
```

But… if you use `-Woverspecs`…
```erlang
  Checking whether the PLT /Users/fernandobenavides/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
user.erl:15:2: Type specification user:id_from_binary
          (binary()) -> id() is a subtype of the success typing: user:id_from_binary
          (_) -> any()
 done in 0m0.24s
done (warnings were emitted)
```

**Comment by elbrujohalcon** [comment] 2022-04-25 14:00
It gets even weirder if you remove the spec from `id_from_binary/1`…
```erlang
-module(user).

-export([from_binary/1]).
-export_type([id/0, user/0]).

-record(user, {id :: id()}).

-opaque user() :: #user{}.
-opaque id() :: binary().

-spec from_binary(binary()) -> user().
from_binary(B) ->
  #user{id = id_from_binary(B)}.

id_from_binary(B) -> B.
```

```erlang
$ dialyzer *.erl -Woverspecs
  Checking whether the PLT  ~/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
user.erl:11:2: Type specification user:from_binary
          (binary()) -> user() is a subtype of the success typing: user:from_binary
          (_) -> user:user()
 done in 0m0.21s
done (warnings were emitted)
```

**Comment by michallepicki** [comment] 2022-04-25 17:04
> But now dialyzer is requiring that in order to call this "constructor" function, I need to already have the opaque value probably by calling the constructor function.

As I understand this is because the inner field is marked as opaque as well. If the only requirement you want to declare is that the record must be constructed only in that module, then it is enough to mark only the record type as opaque. Marking the inner field type as opaque as well means that this field's value also needs to be come from this module.

**Closed** 2022-05-03 13:51 UTC
Labels: team:VM, bug
