### ISSUE TITLE
[erlc] internal consistency check failed on bs_get_integer2: "unassigned"

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6614] opened 2023-01-02 09:59 UTC
On master,
```erlang
f([X | Y]) ->
    try
        ([ok || _ <- Y] > catch <<ok>>) xor false
    catch
        <<Z:X>> ->
            Z
    end.
```
crashes erlc with the error message:
```
bs_get_integer2:1: function f/1+29:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_get_integer2,
                   {f,13},
                   4,
                   [{tr,{x,3},{t_bs_context,1}},
                    {y,1},
                    1,
                    {field_flags,
                        [{anno,[13,{file,"minimized/bs_get_integer2.erl"}]},
                         unsigned,big]}],
                   {x,4}}
  Error:       {unassigned,{y,1}}:
```

This might be a duplicate of https://github.com/erlang/otp/issues/6603, since both show `Error: {unassigned, {y, `. I am filing it separately because it triggers on a different instruction (`bs_get_integer2` vs `move`), with rather different testcases.

**Comment by jhogberg** [comment] 2023-01-02 14:48
Thanks for your report, closing this as duplicate of #6603 :)

**Closed by jhogberg** 2023-01-02 14:48 UTC
Labels: team:VM, bug
